#include "link.h"

namespace LuaApi {

void Link::registerEnums(Lua::State& state)
{
    (void)state;
    
#define INTABLE(count) state.createtable(0,count)
#define ENDTABLE(name) state.setglobal(name)
#define ADDVAR(name, value) state.pushinteger(value); state.setfield(-2, name)
    
    // KeyMod.Shift
    INTABLE(5);
    ADDVAR("Shift", Qt::ShiftModifier);
    ADDVAR("Control", Qt::ControlModifier);
    ADDVAR("Alt", Qt::AltModifier);
    ADDVAR("Meta", Qt::MetaModifier);
    ADDVAR("Keypad", Qt::KeypadModifier);
    ENDTABLE("KeyMod");
    
    // Mouse.Left
    INTABLE(31);
    ADDVAR("Left",Qt::LeftButton);
    ADDVAR("Mid",Qt::MidButton);
    ADDVAR("Middle",Qt::MiddleButton);
    ADDVAR("Right",Qt::RightButton);
    ADDVAR("Back",Qt::BackButton);
    ADDVAR("Forward",Qt::ForwardButton);
    ADDVAR("Task",Qt::TaskButton);
    ADDVAR("Extra1",Qt::ExtraButton1);
    ADDVAR("Extra2",Qt::ExtraButton2);
    ADDVAR("Extra3",Qt::ExtraButton3);
    ADDVAR("Extra4",Qt::ExtraButton4);
    ADDVAR("Extra5",Qt::ExtraButton5);
    ADDVAR("Extra6",Qt::ExtraButton6);
    ADDVAR("Extra7",Qt::ExtraButton7);
    ADDVAR("Extra8",Qt::ExtraButton8);
    ADDVAR("Extra9",Qt::ExtraButton9);
    ADDVAR("Extra10",Qt::ExtraButton10);
    ADDVAR("Extra11",Qt::ExtraButton11);
    ADDVAR("Extra12",Qt::ExtraButton12);
    ADDVAR("Extra13",Qt::ExtraButton13);
    ADDVAR("Extra14",Qt::ExtraButton14);
    ADDVAR("Extra15",Qt::ExtraButton15);
    ADDVAR("Extra16",Qt::ExtraButton16);
    ADDVAR("Extra17",Qt::ExtraButton17);
    ADDVAR("Extra18",Qt::ExtraButton18);
    ADDVAR("Extra19",Qt::ExtraButton19);
    ADDVAR("Extra20",Qt::ExtraButton20);
    ADDVAR("Extra21",Qt::ExtraButton21);
    ADDVAR("Extra22",Qt::ExtraButton22);
    ADDVAR("Extra23",Qt::ExtraButton23);
    ADDVAR("Extra24",Qt::ExtraButton24);
    ENDTABLE("Mouse");
    
    // Key.Escape
    INTABLE(450);
    ADDVAR("Escape", Qt::Key_Escape);
    ADDVAR("Tab", Qt::Key_Tab);
    ADDVAR("Backtab", Qt::Key_Backtab);
    ADDVAR("Backspace", Qt::Key_Backspace);
    ADDVAR("Return", Qt::Key_Return);
    ADDVAR("Enter", Qt::Key_Enter);
    ADDVAR("Insert", Qt::Key_Insert);
    ADDVAR("Delete", Qt::Key_Delete);
    ADDVAR("Pause", Qt::Key_Pause);
    ADDVAR("Print", Qt::Key_Print);
    ADDVAR("SysReq", Qt::Key_SysReq);
    ADDVAR("Clear", Qt::Key_Clear);
    ADDVAR("Home", Qt::Key_Home);
    ADDVAR("End", Qt::Key_End);
    ADDVAR("Left", Qt::Key_Left);
    ADDVAR("Up", Qt::Key_Up);
    ADDVAR("Right", Qt::Key_Right);
    ADDVAR("Down", Qt::Key_Down);
    ADDVAR("PageUp", Qt::Key_PageUp);
    ADDVAR("PageDown", Qt::Key_PageDown);
    ADDVAR("Shift", Qt::Key_Shift);
    ADDVAR("Control", Qt::Key_Control);
    ADDVAR("Meta", Qt::Key_Meta);
    ADDVAR("Alt", Qt::Key_Alt);
    ADDVAR("AltGr", Qt::Key_AltGr);
    ADDVAR("CapsLock", Qt::Key_CapsLock);
    ADDVAR("NumLock", Qt::Key_NumLock);
    ADDVAR("ScrollLock", Qt::Key_ScrollLock);
    ADDVAR("F1", Qt::Key_F1);
    ADDVAR("F2", Qt::Key_F2);
    ADDVAR("F3", Qt::Key_F3);
    ADDVAR("F4", Qt::Key_F4);
    ADDVAR("F5", Qt::Key_F5);
    ADDVAR("F6", Qt::Key_F6);
    ADDVAR("F7", Qt::Key_F7);
    ADDVAR("F8", Qt::Key_F8);
    ADDVAR("F9", Qt::Key_F9);
    ADDVAR("F10", Qt::Key_F10);
    ADDVAR("F11", Qt::Key_F11);
    ADDVAR("F12", Qt::Key_F12);
    ADDVAR("F13", Qt::Key_F13);
    ADDVAR("F14", Qt::Key_F14);
    ADDVAR("F15", Qt::Key_F15);
    ADDVAR("F16", Qt::Key_F16);
    ADDVAR("F17", Qt::Key_F17);
    ADDVAR("F18", Qt::Key_F18);
    ADDVAR("F19", Qt::Key_F19);
    ADDVAR("F20", Qt::Key_F20);
    ADDVAR("F21", Qt::Key_F21);
    ADDVAR("F22", Qt::Key_F22);
    ADDVAR("F23", Qt::Key_F23);
    ADDVAR("F24", Qt::Key_F24);
    ADDVAR("F25", Qt::Key_F25);
    ADDVAR("F26", Qt::Key_F26);
    ADDVAR("F27", Qt::Key_F27);
    ADDVAR("F28", Qt::Key_F28);
    ADDVAR("F29", Qt::Key_F29);
    ADDVAR("F30", Qt::Key_F30);
    ADDVAR("F31", Qt::Key_F31);
    ADDVAR("F32", Qt::Key_F32);
    ADDVAR("F33", Qt::Key_F33);
    ADDVAR("F34", Qt::Key_F34);
    ADDVAR("F35", Qt::Key_F35);
    ADDVAR("Super_L", Qt::Key_Super_L);
    ADDVAR("Super_R", Qt::Key_Super_R);
    ADDVAR("Menu", Qt::Key_Menu);
    ADDVAR("Hyper_L", Qt::Key_Hyper_L);
    ADDVAR("Hyper_R", Qt::Key_Hyper_R);
    ADDVAR("Help", Qt::Key_Help);
    ADDVAR("Direction_L", Qt::Key_Direction_L);
    ADDVAR("Direction_R", Qt::Key_Direction_R);
    ADDVAR("Space", Qt::Key_Space);
    ADDVAR("Any", Qt::Key_Any);
    ADDVAR("Exclam", Qt::Key_Exclam);
    ADDVAR("QuoteDbl", Qt::Key_QuoteDbl);
    ADDVAR("NumberSign", Qt::Key_NumberSign);
    ADDVAR("Dollar", Qt::Key_Dollar);
    ADDVAR("Percent", Qt::Key_Percent);
    ADDVAR("Ampersand", Qt::Key_Ampersand);
    ADDVAR("Apostrophe", Qt::Key_Apostrophe);
    ADDVAR("ParenLeft", Qt::Key_ParenLeft);
    ADDVAR("ParenRight", Qt::Key_ParenRight);
    ADDVAR("Asterisk", Qt::Key_Asterisk);
    ADDVAR("Plus", Qt::Key_Plus);
    ADDVAR("Comma", Qt::Key_Comma);
    ADDVAR("Minus", Qt::Key_Minus);
    ADDVAR("Period", Qt::Key_Period);
    ADDVAR("Slash", Qt::Key_Slash);
    ADDVAR("0", Qt::Key_0);
    ADDVAR("1", Qt::Key_1);
    ADDVAR("2", Qt::Key_2);
    ADDVAR("3", Qt::Key_3);
    ADDVAR("4", Qt::Key_4);
    ADDVAR("5", Qt::Key_5);
    ADDVAR("6", Qt::Key_6);
    ADDVAR("7", Qt::Key_7);
    ADDVAR("8", Qt::Key_8);
    ADDVAR("9", Qt::Key_9);
    ADDVAR("Colon", Qt::Key_Colon);
    ADDVAR("Semicolon", Qt::Key_Semicolon);
    ADDVAR("Less", Qt::Key_Less);
    ADDVAR("Equal", Qt::Key_Equal);
    ADDVAR("Greater", Qt::Key_Greater);
    ADDVAR("Question", Qt::Key_Question);
    ADDVAR("At", Qt::Key_At);
    ADDVAR("A", Qt::Key_A);
    ADDVAR("B", Qt::Key_B);
    ADDVAR("C", Qt::Key_C);
    ADDVAR("D", Qt::Key_D);
    ADDVAR("E", Qt::Key_E);
    ADDVAR("F", Qt::Key_F);
    ADDVAR("G", Qt::Key_G);
    ADDVAR("H", Qt::Key_H);
    ADDVAR("I", Qt::Key_I);
    ADDVAR("J", Qt::Key_J);
    ADDVAR("K", Qt::Key_K);
    ADDVAR("L", Qt::Key_L);
    ADDVAR("M", Qt::Key_M);
    ADDVAR("N", Qt::Key_N);
    ADDVAR("O", Qt::Key_O);
    ADDVAR("P", Qt::Key_P);
    ADDVAR("Q", Qt::Key_Q);
    ADDVAR("R", Qt::Key_R);
    ADDVAR("S", Qt::Key_S);
    ADDVAR("T", Qt::Key_T);
    ADDVAR("U", Qt::Key_U);
    ADDVAR("V", Qt::Key_V);
    ADDVAR("W", Qt::Key_W);
    ADDVAR("X", Qt::Key_X);
    ADDVAR("Y", Qt::Key_Y);
    ADDVAR("Z", Qt::Key_Z);
    ADDVAR("BracketLeft", Qt::Key_BracketLeft);
    ADDVAR("Backslash", Qt::Key_Backslash);
    ADDVAR("BracketRight", Qt::Key_BracketRight);
    ADDVAR("AsciiCircum", Qt::Key_AsciiCircum);
    ADDVAR("Underscore", Qt::Key_Underscore);
    ADDVAR("QuoteLeft", Qt::Key_QuoteLeft);
    ADDVAR("BraceLeft", Qt::Key_BraceLeft);
    ADDVAR("Bar", Qt::Key_Bar);
    ADDVAR("BraceRight", Qt::Key_BraceRight);
    ADDVAR("AsciiTilde", Qt::Key_AsciiTilde);
    ADDVAR("nobreakspace", Qt::Key_nobreakspace);
    ADDVAR("exclamdown", Qt::Key_exclamdown);
    ADDVAR("cent", Qt::Key_cent);
    ADDVAR("sterling", Qt::Key_sterling);
    ADDVAR("currency", Qt::Key_currency);
    ADDVAR("yen", Qt::Key_yen);
    ADDVAR("brokenbar", Qt::Key_brokenbar);
    ADDVAR("section", Qt::Key_section);
    ADDVAR("diaeresis", Qt::Key_diaeresis);
    ADDVAR("copyright", Qt::Key_copyright);
    ADDVAR("ordfeminine", Qt::Key_ordfeminine);
    ADDVAR("guillemotleft", Qt::Key_guillemotleft);
    ADDVAR("notsign", Qt::Key_notsign);
    ADDVAR("hyphen", Qt::Key_hyphen);
    ADDVAR("registered", Qt::Key_registered);
    ADDVAR("macron", Qt::Key_macron);
    ADDVAR("degree", Qt::Key_degree);
    ADDVAR("plusminus", Qt::Key_plusminus);
    ADDVAR("twosuperior", Qt::Key_twosuperior);
    ADDVAR("threesuperior", Qt::Key_threesuperior);
    ADDVAR("acute", Qt::Key_acute);
    ADDVAR("mu", Qt::Key_mu);
    ADDVAR("paragraph", Qt::Key_paragraph);
    ADDVAR("periodcentered", Qt::Key_periodcentered);
    ADDVAR("cedilla", Qt::Key_cedilla);
    ADDVAR("onesuperior", Qt::Key_onesuperior);
    ADDVAR("masculine", Qt::Key_masculine);
    ADDVAR("guillemotright", Qt::Key_guillemotright);
    ADDVAR("onequarter", Qt::Key_onequarter);
    ADDVAR("onehalf", Qt::Key_onehalf);
    ADDVAR("threequarters", Qt::Key_threequarters);
    ADDVAR("questiondown", Qt::Key_questiondown);
    ADDVAR("Agrave", Qt::Key_Agrave);
    ADDVAR("Aacute", Qt::Key_Aacute);
    ADDVAR("Acircumflex", Qt::Key_Acircumflex);
    ADDVAR("Atilde", Qt::Key_Atilde);
    ADDVAR("Adiaeresis", Qt::Key_Adiaeresis);
    ADDVAR("Aring", Qt::Key_Aring);
    ADDVAR("AE", Qt::Key_AE);
    ADDVAR("Ccedilla", Qt::Key_Ccedilla);
    ADDVAR("Egrave", Qt::Key_Egrave);
    ADDVAR("Eacute", Qt::Key_Eacute);
    ADDVAR("Ecircumflex", Qt::Key_Ecircumflex);
    ADDVAR("Ediaeresis", Qt::Key_Ediaeresis);
    ADDVAR("Igrave", Qt::Key_Igrave);
    ADDVAR("Iacute", Qt::Key_Iacute);
    ADDVAR("Icircumflex", Qt::Key_Icircumflex);
    ADDVAR("Idiaeresis", Qt::Key_Idiaeresis);
    ADDVAR("ETH", Qt::Key_ETH);
    ADDVAR("Ntilde", Qt::Key_Ntilde);
    ADDVAR("Ograve", Qt::Key_Ograve);
    ADDVAR("Oacute", Qt::Key_Oacute);
    ADDVAR("Ocircumflex", Qt::Key_Ocircumflex);
    ADDVAR("Otilde", Qt::Key_Otilde);
    ADDVAR("Odiaeresis", Qt::Key_Odiaeresis);
    ADDVAR("multiply", Qt::Key_multiply);
    ADDVAR("Ooblique", Qt::Key_Ooblique);
    ADDVAR("Ugrave", Qt::Key_Ugrave);
    ADDVAR("Uacute", Qt::Key_Uacute);
    ADDVAR("Ucircumflex", Qt::Key_Ucircumflex);
    ADDVAR("Udiaeresis", Qt::Key_Udiaeresis);
    ADDVAR("Yacute", Qt::Key_Yacute);
    ADDVAR("THORN", Qt::Key_THORN);
    ADDVAR("ssharp", Qt::Key_ssharp);
    ADDVAR("division", Qt::Key_division);
    ADDVAR("ydiaeresis", Qt::Key_ydiaeresis);
    ADDVAR("Multi_key", Qt::Key_Multi_key);
    ADDVAR("Codeinput", Qt::Key_Codeinput);
    ADDVAR("SingleCandidate", Qt::Key_SingleCandidate);
    ADDVAR("MultipleCandidate", Qt::Key_MultipleCandidate);
    ADDVAR("PreviousCandidate", Qt::Key_PreviousCandidate);
    ADDVAR("Mode_switch", Qt::Key_Mode_switch);
    ADDVAR("Kanji", Qt::Key_Kanji);
    ADDVAR("Muhenkan", Qt::Key_Muhenkan);
    ADDVAR("Henkan", Qt::Key_Henkan);
    ADDVAR("Romaji", Qt::Key_Romaji);
    ADDVAR("Hiragana", Qt::Key_Hiragana);
    ADDVAR("Katakana", Qt::Key_Katakana);
    ADDVAR("Hiragana_Katakana", Qt::Key_Hiragana_Katakana);
    ADDVAR("Zenkaku", Qt::Key_Zenkaku);
    ADDVAR("Hankaku", Qt::Key_Hankaku);
    ADDVAR("Zenkaku_Hankaku", Qt::Key_Zenkaku_Hankaku);
    ADDVAR("Touroku", Qt::Key_Touroku);
    ADDVAR("Massyo", Qt::Key_Massyo);
    ADDVAR("Kana_Lock", Qt::Key_Kana_Lock);
    ADDVAR("Kana_Shift", Qt::Key_Kana_Shift);
    ADDVAR("Eisu_Shift", Qt::Key_Eisu_Shift);
    ADDVAR("Eisu_toggle", Qt::Key_Eisu_toggle);
    ADDVAR("Hangul", Qt::Key_Hangul);
    ADDVAR("Hangul_Start", Qt::Key_Hangul_Start);
    ADDVAR("Hangul_End", Qt::Key_Hangul_End);
    ADDVAR("Hangul_Hanja", Qt::Key_Hangul_Hanja);
    ADDVAR("Hangul_Jamo", Qt::Key_Hangul_Jamo);
    ADDVAR("Hangul_Romaja", Qt::Key_Hangul_Romaja);
    ADDVAR("Hangul_Jeonja", Qt::Key_Hangul_Jeonja);
    ADDVAR("Hangul_Banja", Qt::Key_Hangul_Banja);
    ADDVAR("Hangul_PreHanja", Qt::Key_Hangul_PreHanja);
    ADDVAR("Hangul_PostHanja", Qt::Key_Hangul_PostHanja);
    ADDVAR("Hangul_Special", Qt::Key_Hangul_Special);
    ADDVAR("Dead_Grave", Qt::Key_Dead_Grave);
    ADDVAR("Dead_Acute", Qt::Key_Dead_Acute);
    ADDVAR("Dead_Circumflex", Qt::Key_Dead_Circumflex);
    ADDVAR("Dead_Tilde", Qt::Key_Dead_Tilde);
    ADDVAR("Dead_Macron", Qt::Key_Dead_Macron);
    ADDVAR("Dead_Breve", Qt::Key_Dead_Breve);
    ADDVAR("Dead_Abovedot", Qt::Key_Dead_Abovedot);
    ADDVAR("Dead_Diaeresis", Qt::Key_Dead_Diaeresis);
    ADDVAR("Dead_Abovering", Qt::Key_Dead_Abovering);
    ADDVAR("Dead_Doubleacute", Qt::Key_Dead_Doubleacute);
    ADDVAR("Dead_Caron", Qt::Key_Dead_Caron);
    ADDVAR("Dead_Cedilla", Qt::Key_Dead_Cedilla);
    ADDVAR("Dead_Ogonek", Qt::Key_Dead_Ogonek);
    ADDVAR("Dead_Iota", Qt::Key_Dead_Iota);
    ADDVAR("Dead_Voiced_Sound", Qt::Key_Dead_Voiced_Sound);
    ADDVAR("Dead_Semivoiced_Sound", Qt::Key_Dead_Semivoiced_Sound);
    ADDVAR("Dead_Belowdot", Qt::Key_Dead_Belowdot);
    ADDVAR("Dead_Hook", Qt::Key_Dead_Hook);
    ADDVAR("Dead_Horn", Qt::Key_Dead_Horn);
    ADDVAR("Back", Qt::Key_Back);
    ADDVAR("Forward", Qt::Key_Forward);
    ADDVAR("Stop", Qt::Key_Stop);
    ADDVAR("Refresh", Qt::Key_Refresh);
    ADDVAR("VolumeDown", Qt::Key_VolumeDown);
    ADDVAR("VolumeMute", Qt::Key_VolumeMute);
    ADDVAR("VolumeUp", Qt::Key_VolumeUp);
    ADDVAR("BassBoost", Qt::Key_BassBoost);
    ADDVAR("BassUp", Qt::Key_BassUp);
    ADDVAR("BassDown", Qt::Key_BassDown);
    ADDVAR("TrebleUp", Qt::Key_TrebleUp);
    ADDVAR("TrebleDown", Qt::Key_TrebleDown);
    ADDVAR("MediaPlay", Qt::Key_MediaPlay);
    ADDVAR("MediaStop", Qt::Key_MediaStop);
    ADDVAR("MediaPrevious", Qt::Key_MediaPrevious);
    ADDVAR("MediaNext", Qt::Key_MediaNext);
    ADDVAR("MediaRecord", Qt::Key_MediaRecord);
    ADDVAR("MediaPause", Qt::Key_MediaPause);
    ADDVAR("MediaTogglePlayPause", Qt::Key_MediaTogglePlayPause);
    ADDVAR("HomePage", Qt::Key_HomePage);
    ADDVAR("Favorites", Qt::Key_Favorites);
    ADDVAR("Search", Qt::Key_Search);
    ADDVAR("Standby", Qt::Key_Standby);
    ADDVAR("OpenUrl", Qt::Key_OpenUrl);
    ADDVAR("LaunchMail", Qt::Key_LaunchMail);
    ADDVAR("LaunchMedia", Qt::Key_LaunchMedia);
    ADDVAR("Launch0", Qt::Key_Launch0);
    ADDVAR("Launch1", Qt::Key_Launch1);
    ADDVAR("Launch2", Qt::Key_Launch2);
    ADDVAR("Launch3", Qt::Key_Launch3);
    ADDVAR("Launch4", Qt::Key_Launch4);
    ADDVAR("Launch5", Qt::Key_Launch5);
    ADDVAR("Launch6", Qt::Key_Launch6);
    ADDVAR("Launch7", Qt::Key_Launch7);
    ADDVAR("Launch8", Qt::Key_Launch8);
    ADDVAR("Launch9", Qt::Key_Launch9);
    ADDVAR("LaunchA", Qt::Key_LaunchA);
    ADDVAR("LaunchB", Qt::Key_LaunchB);
    ADDVAR("LaunchC", Qt::Key_LaunchC);
    ADDVAR("LaunchD", Qt::Key_LaunchD);
    ADDVAR("LaunchE", Qt::Key_LaunchE);
    ADDVAR("LaunchF", Qt::Key_LaunchF);
    ADDVAR("LaunchG", Qt::Key_LaunchG);
    ADDVAR("LaunchH", Qt::Key_LaunchH);
    ADDVAR("MonBrightnessUp", Qt::Key_MonBrightnessUp);
    ADDVAR("MonBrightnessDown", Qt::Key_MonBrightnessDown);
    ADDVAR("KeyboardLightOnOff", Qt::Key_KeyboardLightOnOff);
    ADDVAR("KeyboardBrightnessUp", Qt::Key_KeyboardBrightnessUp);
    ADDVAR("KeyboardBrightnessDown", Qt::Key_KeyboardBrightnessDown);
    ADDVAR("PowerOff", Qt::Key_PowerOff);
    ADDVAR("WakeUp", Qt::Key_WakeUp);
    ADDVAR("Eject", Qt::Key_Eject);
    ADDVAR("ScreenSaver", Qt::Key_ScreenSaver);
    ADDVAR("WWW", Qt::Key_WWW);
    ADDVAR("Memo", Qt::Key_Memo);
    ADDVAR("LightBulb", Qt::Key_LightBulb);
    ADDVAR("Shop", Qt::Key_Shop);
    ADDVAR("History", Qt::Key_History);
    ADDVAR("AddFavorite", Qt::Key_AddFavorite);
    ADDVAR("HotLinks", Qt::Key_HotLinks);
    ADDVAR("BrightnessAdjust", Qt::Key_BrightnessAdjust);
    ADDVAR("Finance", Qt::Key_Finance);
    ADDVAR("Community", Qt::Key_Community);
    ADDVAR("AudioRewind", Qt::Key_AudioRewind);
    ADDVAR("BackForward", Qt::Key_BackForward);
    ADDVAR("ApplicationLeft", Qt::Key_ApplicationLeft);
    ADDVAR("ApplicationRight", Qt::Key_ApplicationRight);
    ADDVAR("Book", Qt::Key_Book);
    ADDVAR("CD", Qt::Key_CD);
    ADDVAR("Calculator", Qt::Key_Calculator);
    ADDVAR("ToDoList", Qt::Key_ToDoList);
    ADDVAR("ClearGrab", Qt::Key_ClearGrab);
    ADDVAR("Close", Qt::Key_Close);
    ADDVAR("Copy", Qt::Key_Copy);
    ADDVAR("Cut", Qt::Key_Cut);
    ADDVAR("Display", Qt::Key_Display);
    ADDVAR("DOS", Qt::Key_DOS);
    ADDVAR("Documents", Qt::Key_Documents);
    ADDVAR("Excel", Qt::Key_Excel);
    ADDVAR("Explorer", Qt::Key_Explorer);
    ADDVAR("Game", Qt::Key_Game);
    ADDVAR("Go", Qt::Key_Go);
    ADDVAR("iTouch", Qt::Key_iTouch);
    ADDVAR("LogOff", Qt::Key_LogOff);
    ADDVAR("Market", Qt::Key_Market);
    ADDVAR("Meeting", Qt::Key_Meeting);
    ADDVAR("MenuKB", Qt::Key_MenuKB);
    ADDVAR("MenuPB", Qt::Key_MenuPB);
    ADDVAR("MySites", Qt::Key_MySites);
    ADDVAR("News", Qt::Key_News);
    ADDVAR("OfficeHome", Qt::Key_OfficeHome);
    ADDVAR("Option", Qt::Key_Option);
    ADDVAR("Paste", Qt::Key_Paste);
    ADDVAR("Phone", Qt::Key_Phone);
    ADDVAR("Calendar", Qt::Key_Calendar);
    ADDVAR("Reply", Qt::Key_Reply);
    ADDVAR("Reload", Qt::Key_Reload);
    ADDVAR("RotateWindows", Qt::Key_RotateWindows);
    ADDVAR("RotationPB", Qt::Key_RotationPB);
    ADDVAR("RotationKB", Qt::Key_RotationKB);
    ADDVAR("Save", Qt::Key_Save);
    ADDVAR("Send", Qt::Key_Send);
    ADDVAR("Spell", Qt::Key_Spell);
    ADDVAR("SplitScreen", Qt::Key_SplitScreen);
    ADDVAR("Support", Qt::Key_Support);
    ADDVAR("TaskPane", Qt::Key_TaskPane);
    ADDVAR("Terminal", Qt::Key_Terminal);
    ADDVAR("Tools", Qt::Key_Tools);
    ADDVAR("Travel", Qt::Key_Travel);
    ADDVAR("Video", Qt::Key_Video);
    ADDVAR("Word", Qt::Key_Word);
    ADDVAR("Xfer", Qt::Key_Xfer);
    ADDVAR("ZoomIn", Qt::Key_ZoomIn);
    ADDVAR("ZoomOut", Qt::Key_ZoomOut);
    ADDVAR("Away", Qt::Key_Away);
    ADDVAR("Messenger", Qt::Key_Messenger);
    ADDVAR("WebCam", Qt::Key_WebCam);
    ADDVAR("MailForward", Qt::Key_MailForward);
    ADDVAR("Pictures", Qt::Key_Pictures);
    ADDVAR("Music", Qt::Key_Music);
    ADDVAR("Battery", Qt::Key_Battery);
    ADDVAR("Bluetooth", Qt::Key_Bluetooth);
    ADDVAR("WLAN", Qt::Key_WLAN);
    ADDVAR("UWB", Qt::Key_UWB);
    ADDVAR("AudioForward", Qt::Key_AudioForward);
    ADDVAR("AudioRepeat", Qt::Key_AudioRepeat);
    ADDVAR("AudioRandomPlay", Qt::Key_AudioRandomPlay);
    ADDVAR("Subtitle", Qt::Key_Subtitle);
    ADDVAR("AudioCycleTrack", Qt::Key_AudioCycleTrack);
    ADDVAR("Time", Qt::Key_Time);
    ADDVAR("Hibernate", Qt::Key_Hibernate);
    ADDVAR("View", Qt::Key_View);
    ADDVAR("TopMenu", Qt::Key_TopMenu);
    ADDVAR("PowerDown", Qt::Key_PowerDown);
    ADDVAR("Suspend", Qt::Key_Suspend);
    ADDVAR("ContrastAdjust", Qt::Key_ContrastAdjust);
    ADDVAR("TouchpadToggle", Qt::Key_TouchpadToggle);
    ADDVAR("TouchpadOn", Qt::Key_TouchpadOn);
    ADDVAR("TouchpadOff", Qt::Key_TouchpadOff);
    ADDVAR("MicMute", Qt::Key_MicMute);
    ADDVAR("Red", Qt::Key_Red);
    ADDVAR("Green", Qt::Key_Green);
    ADDVAR("Yellow", Qt::Key_Yellow);
    ADDVAR("Blue", Qt::Key_Blue);
    ADDVAR("ChannelUp", Qt::Key_ChannelUp);
    ADDVAR("ChannelDown", Qt::Key_ChannelDown);
    ADDVAR("Guide", Qt::Key_Guide);
    ADDVAR("Info", Qt::Key_Info);
    ADDVAR("Settings", Qt::Key_Settings);
    ADDVAR("MicVolumeUp", Qt::Key_MicVolumeUp);
    ADDVAR("MicVolumeDown", Qt::Key_MicVolumeDown);
    ADDVAR("New", Qt::Key_New);
    ADDVAR("Open", Qt::Key_Open);
    ADDVAR("Find", Qt::Key_Find);
    ADDVAR("Undo", Qt::Key_Undo);
    ADDVAR("Redo", Qt::Key_Redo);
    ADDVAR("MediaLast", Qt::Key_MediaLast);
    ADDVAR("unknown", Qt::Key_unknown);
    ADDVAR("Call", Qt::Key_Call);
    ADDVAR("Camera", Qt::Key_Camera);
    ADDVAR("CameraFocus", Qt::Key_CameraFocus);
    ADDVAR("Context1", Qt::Key_Context1);
    ADDVAR("Context2", Qt::Key_Context2);
    ADDVAR("Context3", Qt::Key_Context3);
    ADDVAR("Context4", Qt::Key_Context4);
    ADDVAR("Flip", Qt::Key_Flip);
    ADDVAR("Hangup", Qt::Key_Hangup);
    ADDVAR("No", Qt::Key_No);
    ADDVAR("Select", Qt::Key_Select);
    ADDVAR("Yes", Qt::Key_Yes);
    ADDVAR("ToggleCallHangup", Qt::Key_ToggleCallHangup);
    ADDVAR("VoiceDial", Qt::Key_VoiceDial);
    ADDVAR("LastNumberRedial", Qt::Key_LastNumberRedial);
    ADDVAR("Execute", Qt::Key_Execute);
    ADDVAR("Printer", Qt::Key_Printer);
    ADDVAR("Play", Qt::Key_Play);
    ADDVAR("Sleep", Qt::Key_Sleep);
    ADDVAR("Zoom", Qt::Key_Zoom);
    ADDVAR("Exit", Qt::Key_Exit);
    ADDVAR("Cancel", Qt::Key_Cancel);
    ADDVAR("MicVolumeUp", Qt::Key_MicVolumeUp);
    ADDVAR("Find", Qt::Key_Find);
    ADDVAR("Open", Qt::Key_Open);
    ADDVAR("MicVolumeDown", Qt::Key_MicVolumeDown);
    ADDVAR("New", Qt::Key_New);
    ADDVAR("Settings", Qt::Key_Settings);
    ADDVAR("Redo", Qt::Key_Redo);
    ADDVAR("Exit", Qt::Key_Exit);
    ADDVAR("Info", Qt::Key_Info);
    ADDVAR("Undo", Qt::Key_Undo);
    ADDVAR("Guide", Qt::Key_Guide);
    ENDTABLE("Key");

    // Base: 18
    // AL_EXT_float32: 2
    // AL_EXT_double: 2
    // AL_EXT_MCFORMATS: 15
    int count = 18;
#ifdef AL_EXT_float32
    count += 2;
#endif
#ifdef AL_EXT_double
    count += 2;
#endif
#ifdef AL_EXT_MCFORMATS
    count += 15;
#endif
    INTABLE(count);
    ADDVAR("UNDETERMINED",SST_UNDETERMINED);
    ADDVAR("STATIC",SST_STATIC);
    ADDVAR("STREAMING",SST_STREAMING);
    ADDVAR("INITIAL",SSS_INITIAL);
    ADDVAR("PLAYING",SSS_PLAYING);
    ADDVAR("PAUSED",SSS_PAUSED);
    ADDVAR("STOPPED",SSS_STOPPED);
    ADDVAR("INVERSE_DISTANCE",SDM_INVERSE_DISTANCE);
    ADDVAR("INVERSE_DISTANCE_CLAMPED",SDM_INVERSE_DISTANCE_CLAMPED);
    ADDVAR("LINEAR_DISTANCE",SDM_LINEAR_DISTANCE);
    ADDVAR("LINEAR_DISTANCE_CLAMPED",SDM_LINEAR_DISTANCE_CLAMPED);
    ADDVAR("EXPONENT_DISTANCE",SDM_EXPONENT_DISTANCE);
    ADDVAR("EXPONENT_DISTANCE_CLAMPED",SDM_EXPONENT_DISTANCE_CLAMPED);
    ADDVAR("INVALID",SBF_INVALID);
    ADDVAR("MONO8",SBF_MONO_8);
    ADDVAR("MONO16",SBF_MONO_16);
    ADDVAR("STEREO8",SBF_STEREO_8);
    ADDVAR("STEREO16",SBF_STEREO_16);
#ifdef AL_EXT_float32
    ADDVAR("MONO_FLOAT32",SBF_MONO_F32);
    ADDVAR("STEREO_FLOAT32",SBF_STEREO_F32);
#endif
#ifdef AL_EXT_double
    ADDVAR("MONO_DOUBLE",SBF_MONO_DOUBLE);
    ADDVAR("STEREO_DOUBLE",SBF_STEREO_DOUBLE);
#endif
#ifdef AL_EXT_MCFORMATS
    ADDVAR("QUAD8",SBF_QUAD_8);
    ADDVAR("QUAD16",SBF_QUAD_16);
    ADDVAR("QUAD32",SBF_QUAD_32);
    ADDVAR("REAR8",SBF_REAR_8);
    ADDVAR("REAR16",SBF_REAR_16);
    ADDVAR("REAR32",SBF_REAR_32);
    ADDVAR("CHN51_8",SBF_51CHN_8);
    ADDVAR("CHN51_16",SBF_51CHN_16);
    ADDVAR("CHN51_32",SBF_51CHN_32);
    ADDVAR("CHN61_8",SBF_61CHN_8);
    ADDVAR("CHN61_16",SBF_61CHN_16);
    ADDVAR("CHN61_32",SBF_61CHN_32);
    ADDVAR("CHN71_8",SBF_71CHN_8);
    ADDVAR("CHN71_16",SBF_71CHN_16);
    ADDVAR("CHN71_32",SBF_71CHN_32);
#endif
    ENDTABLE("AL");
    
    INTABLE(1337); // Seriously?
    ADDVAR("ACTIVE_ATOMIC_COUNTER_BUFFERS",0x92D9);
    ADDVAR("ACTIVE_ATTRIBUTE_MAX_LENGTH",0x8B8A);
    ADDVAR("ACTIVE_ATTRIBUTES",0x8B89);
    ADDVAR("ACTIVE_PROGRAM",0x8259);
    ADDVAR("ACTIVE_RESOURCES",0x92F5);
    ADDVAR("ACTIVE_SUBROUTINE_MAX_LENGTH",0x8E48);
    ADDVAR("ACTIVE_SUBROUTINE_UNIFORM_LOCATIONS",0x8E47);
    ADDVAR("ACTIVE_SUBROUTINE_UNIFORM_MAX_LENGTH",0x8E49);
    ADDVAR("ACTIVE_SUBROUTINE_UNIFORMS",0x8DE6);
    ADDVAR("ACTIVE_SUBROUTINES",0x8DE5);
    ADDVAR("ACTIVE_TEXTURE",0x84E0);
    ADDVAR("ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH",0x8A35);
    ADDVAR("ACTIVE_UNIFORM_BLOCKS",0x8A36);
    ADDVAR("ACTIVE_UNIFORM_MAX_LENGTH",0x8B87);
    ADDVAR("ACTIVE_UNIFORMS",0x8B86);
    ADDVAR("ACTIVE_VARIABLES",0x9305);
    ADDVAR("ALIASED_LINE_WIDTH_RANGE",0x846E);
    ADDVAR("ALL_BARRIER_BITS",0xFFFFFFFF);
    ADDVAR("ALL_SHADER_BITS",0xFFFFFFFF);
    ADDVAR("ALPHA",0x1906);
    ADDVAR("ALREADY_SIGNALED",0x911A);
    ADDVAR("ALWAYS",0x0207);
    ADDVAR("AND",0x1501);
    ADDVAR("AND_INVERTED",0x1504);
    ADDVAR("AND_REVERSE",0x1502);
    ADDVAR("ANY_SAMPLES_PASSED",0x8C2F);
    ADDVAR("ANY_SAMPLES_PASSED_CONSERVATIVE",0x8D6A);
    ADDVAR("ARRAY_BUFFER",0x8892);
    ADDVAR("ARRAY_BUFFER_BINDING",0x8894);
    ADDVAR("ARRAY_SIZE",0x92FB);
    ADDVAR("ARRAY_STRIDE",0x92FE);
    ADDVAR("ATOMIC_COUNTER_BARRIER_BIT",0x00001000);
    ADDVAR("ATOMIC_COUNTER_BUFFER",0x92C0);
    ADDVAR("ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTER_INDICES",0x92C6);
    ADDVAR("ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTERS",0x92C5);
    ADDVAR("ATOMIC_COUNTER_BUFFER_BINDING",0x92C1);
    ADDVAR("ATOMIC_COUNTER_BUFFER_DATA_SIZE",0x92C4);
    ADDVAR("ATOMIC_COUNTER_BUFFER_INDEX",0x9301);
    ADDVAR("ATOMIC_COUNTER_BUFFER_REFERENCED_BY_COMPUTE_SHADER",0x90ED);
    ADDVAR("ATOMIC_COUNTER_BUFFER_REFERENCED_BY_FRAGMENT_SHADER",0x92CB);
    ADDVAR("ATOMIC_COUNTER_BUFFER_REFERENCED_BY_GEOMETRY_SHADER",0x92CA);
    ADDVAR("ATOMIC_COUNTER_BUFFER_REFERENCED_BY_TESS_CONTROL_SHADER",0x92C8);
    ADDVAR("ATOMIC_COUNTER_BUFFER_REFERENCED_BY_TESS_EVALUATION_SHADER",0x92C9);
    ADDVAR("ATOMIC_COUNTER_BUFFER_REFERENCED_BY_VERTEX_SHADER",0x92C7);
    ADDVAR("ATOMIC_COUNTER_BUFFER_SIZE",0x92C3);
    ADDVAR("ATOMIC_COUNTER_BUFFER_START",0x92C2);
    ADDVAR("ATTACHED_SHADERS",0x8B85);
    ADDVAR("AUTO_GENERATE_MIPMAP",0x8295);
    ADDVAR("BACK",0x0405);
    ADDVAR("BACK_LEFT",0x0402);
    ADDVAR("BACK_RIGHT",0x0403);
    ADDVAR("BGR",0x80E0);
    ADDVAR("BGR_INTEGER",0x8D9A);
    ADDVAR("BGRA",0x80E1);
    ADDVAR("BGRA_INTEGER",0x8D9B);
    ADDVAR("BLEND",0x0BE2);
    ADDVAR("BLEND_DST",0x0BE0);
    ADDVAR("BLEND_DST_ALPHA",0x80CA);
    ADDVAR("BLEND_DST_RGB",0x80C8);
    ADDVAR("BLEND_EQUATION_ALPHA",0x883D);
    ADDVAR("BLEND_EQUATION_RGB",0x8009);
    ADDVAR("BLEND_SRC",0x0BE1);
    ADDVAR("BLEND_SRC_ALPHA",0x80CB);
    ADDVAR("BLEND_SRC_RGB",0x80C9);
    ADDVAR("BLOCK_INDEX",0x92FD);
    ADDVAR("BLUE",0x1905);
    ADDVAR("BLUE_INTEGER",0x8D96);
    ADDVAR("BOOL",0x8B56);
    ADDVAR("BOOL_VEC2",0x8B57);
    ADDVAR("BOOL_VEC3",0x8B58);
    ADDVAR("BOOL_VEC4",0x8B59);
    ADDVAR("BUFFER",0x82E0);
    ADDVAR("BUFFER_ACCESS",0x88BB);
    ADDVAR("BUFFER_ACCESS_FLAGS",0x911F);
    ADDVAR("BUFFER_BINDING",0x9302);
    ADDVAR("BUFFER_DATA_SIZE",0x9303);
    ADDVAR("BUFFER_IMMUTABLE_STORAGE",0x821F);
    ADDVAR("BUFFER_MAP_LENGTH",0x9120);
    ADDVAR("BUFFER_MAP_OFFSET",0x9121);
    ADDVAR("BUFFER_MAP_POINTER",0x88BD);
    ADDVAR("BUFFER_MAPPED",0x88BC);
    ADDVAR("BUFFER_SIZE",0x8764);
    ADDVAR("BUFFER_STORAGE_FLAGS",0x8220);
    ADDVAR("BUFFER_UPDATE_BARRIER_BIT",0x00000200);
    ADDVAR("BUFFER_USAGE",0x8765);
    ADDVAR("BUFFER_VARIABLE",0x92E5);
    ADDVAR("BYTE",0x1400);
    ADDVAR("CAVEAT_SUPPORT",0x82B8);
    ADDVAR("CCW",0x0901);
    ADDVAR("CLAMP_READ_COLOR",0x891C);
    ADDVAR("CLAMP_TO_BORDER",0x812D);
    ADDVAR("CLAMP_TO_EDGE",0x812F);
    ADDVAR("CLEAR",0x1500);
    ADDVAR("CLEAR_BUFFER",0x82B4);
    ADDVAR("CLEAR_TEXTURE",0x9365);
    ADDVAR("CLIENT_MAPPED_BUFFER_BARRIER_BIT",0x00004000);
    ADDVAR("CLIENT_STORAGE_BIT",0x0200);
    ADDVAR("CLIP_DISTANCE0",0x3000);
    ADDVAR("CLIP_DISTANCE1",0x3001);
    ADDVAR("CLIP_DISTANCE2",0x3002);
    ADDVAR("CLIP_DISTANCE3",0x3003);
    ADDVAR("CLIP_DISTANCE4",0x3004);
    ADDVAR("CLIP_DISTANCE5",0x3005);
    ADDVAR("CLIP_DISTANCE6",0x3006);
    ADDVAR("CLIP_DISTANCE7",0x3007);
    ADDVAR("COLOR",0x1800);
    ADDVAR("COLOR_ATTACHMENT0",0x8CE0);
    ADDVAR("COLOR_ATTACHMENT1",0x8CE1);
    ADDVAR("COLOR_ATTACHMENT10",0x8CEA);
    ADDVAR("COLOR_ATTACHMENT11",0x8CEB);
    ADDVAR("COLOR_ATTACHMENT12",0x8CEC);
    ADDVAR("COLOR_ATTACHMENT13",0x8CED);
    ADDVAR("COLOR_ATTACHMENT14",0x8CEE);
    ADDVAR("COLOR_ATTACHMENT15",0x8CEF);
    ADDVAR("COLOR_ATTACHMENT16",0x8CF0);
    ADDVAR("COLOR_ATTACHMENT17",0x8CF1);
    ADDVAR("COLOR_ATTACHMENT18",0x8CF2);
    ADDVAR("COLOR_ATTACHMENT19",0x8CF3);
    ADDVAR("COLOR_ATTACHMENT2",0x8CE2);
    ADDVAR("COLOR_ATTACHMENT20",0x8CF4);
    ADDVAR("COLOR_ATTACHMENT21",0x8CF5);
    ADDVAR("COLOR_ATTACHMENT22",0x8CF6);
    ADDVAR("COLOR_ATTACHMENT23",0x8CF7);
    ADDVAR("COLOR_ATTACHMENT24",0x8CF8);
    ADDVAR("COLOR_ATTACHMENT25",0x8CF9);
    ADDVAR("COLOR_ATTACHMENT26",0x8CFA);
    ADDVAR("COLOR_ATTACHMENT27",0x8CFB);
    ADDVAR("COLOR_ATTACHMENT28",0x8CFC);
    ADDVAR("COLOR_ATTACHMENT29",0x8CFD);
    ADDVAR("COLOR_ATTACHMENT3",0x8CE3);
    ADDVAR("COLOR_ATTACHMENT30",0x8CFE);
    ADDVAR("COLOR_ATTACHMENT31",0x8CFF);
    ADDVAR("COLOR_ATTACHMENT4",0x8CE4);
    ADDVAR("COLOR_ATTACHMENT5",0x8CE5);
    ADDVAR("COLOR_ATTACHMENT6",0x8CE6);
    ADDVAR("COLOR_ATTACHMENT7",0x8CE7);
    ADDVAR("COLOR_ATTACHMENT8",0x8CE8);
    ADDVAR("COLOR_ATTACHMENT9",0x8CE9);
    ADDVAR("COLOR_BUFFER_BIT",0x00004000);
    ADDVAR("COLOR_CLEAR_VALUE",0x0C22);
    ADDVAR("COLOR_COMPONENTS",0x8283);
    ADDVAR("COLOR_ENCODING",0x8296);
    ADDVAR("COLOR_LOGIC_OP",0x0BF2);
    ADDVAR("COLOR_RENDERABLE",0x8286);
    ADDVAR("COLOR_WRITEMASK",0x0C23);
    ADDVAR("COMMAND_BARRIER_BIT",0x00000040);
    ADDVAR("COMPARE_REF_TO_TEXTURE",0x884E);
    ADDVAR("COMPATIBLE_SUBROUTINES",0x8E4B);
    ADDVAR("COMPILE_STATUS",0x8B81);
    ADDVAR("COMPRESSED_R11_EAC",0x9270);
    ADDVAR("COMPRESSED_RED",0x8225);
    ADDVAR("COMPRESSED_RED_RGTC1",0x8DBB);
    ADDVAR("COMPRESSED_RG",0x8226);
    ADDVAR("COMPRESSED_RG_RGTC2",0x8DBD);
    ADDVAR("COMPRESSED_RG11_EAC",0x9272);
    ADDVAR("COMPRESSED_RGB",0x84ED);
    ADDVAR("COMPRESSED_RGB_BPTC_SIGNED_FLOAT",0x8E8E);
    ADDVAR("COMPRESSED_RGB_BPTC_UNSIGNED_FLOAT",0x8E8F);
    ADDVAR("COMPRESSED_RGB8_ETC2",0x9274);
    ADDVAR("COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2",0x9276);
    ADDVAR("COMPRESSED_RGBA",0x84EE);
    ADDVAR("COMPRESSED_RGBA_BPTC_UNORM",0x8E8C);
    ADDVAR("COMPRESSED_RGBA8_ETC2_EAC",0x9278);
    ADDVAR("COMPRESSED_SIGNED_R11_EAC",0x9271);
    ADDVAR("COMPRESSED_SIGNED_RED_RGTC1",0x8DBC);
    ADDVAR("COMPRESSED_SIGNED_RG_RGTC2",0x8DBE);
    ADDVAR("COMPRESSED_SIGNED_RG11_EAC",0x9273);
    ADDVAR("COMPRESSED_SRGB",0x8C48);
    ADDVAR("COMPRESSED_SRGB_ALPHA",0x8C49);
    ADDVAR("COMPRESSED_SRGB_ALPHA_BPTC_UNORM",0x8E8D);
    ADDVAR("COMPRESSED_SRGB8_ALPHA8_ETC2_EAC",0x9279);
    ADDVAR("COMPRESSED_SRGB8_ETC2",0x9275);
    ADDVAR("COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2",0x9277);
    ADDVAR("COMPRESSED_TEXTURE_FORMATS",0x86A3);
    ADDVAR("COMPUTE_SHADER",0x91B9);
    ADDVAR("COMPUTE_SHADER_BIT",0x00000020);
    ADDVAR("COMPUTE_SUBROUTINE",0x92ED);
    ADDVAR("COMPUTE_SUBROUTINE_UNIFORM",0x92F3);
    ADDVAR("COMPUTE_TEXTURE",0x82A0);
    ADDVAR("COMPUTE_WORK_GROUP_SIZE",0x8267);
    ADDVAR("CONDITION_SATISFIED",0x911C);
    ADDVAR("CONSTANT_ALPHA",0x8003);
    ADDVAR("CONSTANT_COLOR",0x8001);
    ADDVAR("CONTEXT_COMPATIBILITY_PROFILE_BIT",0x00000002);
    ADDVAR("CONTEXT_CORE_PROFILE_BIT",0x00000001);
    ADDVAR("CONTEXT_FLAG_DEBUG_BIT",0x00000002);
    ADDVAR("CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT",0x00000001);
    ADDVAR("CONTEXT_FLAGS",0x821E);
    ADDVAR("CONTEXT_PROFILE_MASK",0x9126);
    ADDVAR("COPY",0x1503);
    ADDVAR("COPY_INVERTED",0x150C);
    ADDVAR("COPY_READ_BUFFER",0x8F36);
    ADDVAR("COPY_READ_BUFFER_BINDING",0x8F36);
    ADDVAR("COPY_WRITE_BUFFER",0x8F37);
    ADDVAR("COPY_WRITE_BUFFER_BINDING",0x8F37);
    ADDVAR("CULL_FACE",0x0B44);
    ADDVAR("CULL_FACE_MODE",0x0B45);
    ADDVAR("CURRENT_PROGRAM",0x8B8D);
    ADDVAR("CURRENT_QUERY",0x8865);
    ADDVAR("CURRENT_VERTEX_ATTRIB",0x8626);
    ADDVAR("CW",0x0900);
    ADDVAR("DEBUG_CALLBACK_FUNCTION",0x8244);
    ADDVAR("DEBUG_CALLBACK_USER_PARAM",0x8245);
    ADDVAR("DEBUG_GROUP_STACK_DEPTH",0x826D);
    ADDVAR("DEBUG_LOGGED_MESSAGES",0x9145);
    ADDVAR("DEBUG_NEXT_LOGGED_MESSAGE_LENGTH",0x8243);
    ADDVAR("DEBUG_OUTPUT",0x92E0);
    ADDVAR("DEBUG_OUTPUT_SYNCHRONOUS",0x8242);
    ADDVAR("DEBUG_SEVERITY_HIGH",0x9146);
    ADDVAR("DEBUG_SEVERITY_LOW",0x9148);
    ADDVAR("DEBUG_SEVERITY_MEDIUM",0x9147);
    ADDVAR("DEBUG_SEVERITY_NOTIFICATION",0x826B);
    ADDVAR("DEBUG_SOURCE_API",0x8246);
    ADDVAR("DEBUG_SOURCE_APPLICATION",0x824A);
    ADDVAR("DEBUG_SOURCE_OTHER",0x824B);
    ADDVAR("DEBUG_SOURCE_SHADER_COMPILER",0x8248);
    ADDVAR("DEBUG_SOURCE_THIRD_PARTY",0x8249);
    ADDVAR("DEBUG_SOURCE_WINDOW_SYSTEM",0x8247);
    ADDVAR("DEBUG_TYPE_DEPRECATED_BEHAVIOR",0x824D);
    ADDVAR("DEBUG_TYPE_ERROR",0x824C);
    ADDVAR("DEBUG_TYPE_MARKER",0x8268);
    ADDVAR("DEBUG_TYPE_OTHER",0x8251);
    ADDVAR("DEBUG_TYPE_PERFORMANCE",0x8250);
    ADDVAR("DEBUG_TYPE_POP_GROUP",0x826A);
    ADDVAR("DEBUG_TYPE_PORTABILITY",0x824F);
    ADDVAR("DEBUG_TYPE_PUSH_GROUP",0x8269);
    ADDVAR("DEBUG_TYPE_UNDEFINED_BEHAVIOR",0x824E);
    ADDVAR("DECR",0x1E03);
    ADDVAR("DECR_WRAP",0x8508);
    ADDVAR("DELETE_STATUS",0x8B80);
    ADDVAR("DEPTH",0x1801);
    ADDVAR("DEPTH_ATTACHMENT",0x8D00);
    ADDVAR("DEPTH_BUFFER_BIT",0x00000100);
    ADDVAR("DEPTH_CLAMP",0x864F);
    ADDVAR("DEPTH_CLEAR_VALUE",0x0B73);
    ADDVAR("DEPTH_COMPONENT",0x1902);
    ADDVAR("DEPTH_COMPONENT16",0x81A5);
    ADDVAR("DEPTH_COMPONENT24",0x81A6);
    ADDVAR("DEPTH_COMPONENT32",0x81A7);
    ADDVAR("DEPTH_COMPONENT32F",0x8CAC);
    ADDVAR("DEPTH_COMPONENTS",0x8284);
    ADDVAR("DEPTH_FUNC",0x0B74);
    ADDVAR("DEPTH_RANGE",0x0B70);
    ADDVAR("DEPTH_RENDERABLE",0x8287);
    ADDVAR("DEPTH_STENCIL",0x84F9);
    ADDVAR("DEPTH_STENCIL_ATTACHMENT",0x821A);
    ADDVAR("DEPTH_STENCIL_TEXTURE_MODE",0x90EA);
    ADDVAR("DEPTH_TEST",0x0B71);
    ADDVAR("DEPTH_WRITEMASK",0x0B72);
    ADDVAR("DEPTH24_STENCIL8",0x88F0);
    ADDVAR("DEPTH32F_STENCIL8",0x8CAD);
    ADDVAR("DISPATCH_INDIRECT_BUFFER",0x90EE);
    ADDVAR("DISPATCH_INDIRECT_BUFFER_BINDING",0x90EF);
    ADDVAR("DITHER",0x0BD0);
    ADDVAR("DONT_CARE",0x1100);
    ADDVAR("DOUBLE",0x140A);
    ADDVAR("DOUBLE_MAT2",0x8F46);
    ADDVAR("DOUBLE_MAT2x3",0x8F49);
    ADDVAR("DOUBLE_MAT2x4",0x8F4A);
    ADDVAR("DOUBLE_MAT3",0x8F47);
    ADDVAR("DOUBLE_MAT3x2",0x8F4B);
    ADDVAR("DOUBLE_MAT3x4",0x8F4C);
    ADDVAR("DOUBLE_MAT4",0x8F48);
    ADDVAR("DOUBLE_MAT4x2",0x8F4D);
    ADDVAR("DOUBLE_MAT4x3",0x8F4E);
    ADDVAR("DOUBLE_VEC2",0x8FFC);
    ADDVAR("DOUBLE_VEC3",0x8FFD);
    ADDVAR("DOUBLE_VEC4",0x8FFE);
    ADDVAR("DOUBLEBUFFER",0x0C32);
    ADDVAR("DRAW_BUFFER",0x0C01);
    ADDVAR("DRAW_BUFFER0",0x8825);
    ADDVAR("DRAW_BUFFER1",0x8826);
    ADDVAR("DRAW_BUFFER10",0x882F);
    ADDVAR("DRAW_BUFFER11",0x8830);
    ADDVAR("DRAW_BUFFER12",0x8831);
    ADDVAR("DRAW_BUFFER13",0x8832);
    ADDVAR("DRAW_BUFFER14",0x8833);
    ADDVAR("DRAW_BUFFER15",0x8834);
    ADDVAR("DRAW_BUFFER2",0x8827);
    ADDVAR("DRAW_BUFFER3",0x8828);
    ADDVAR("DRAW_BUFFER4",0x8829);
    ADDVAR("DRAW_BUFFER5",0x882A);
    ADDVAR("DRAW_BUFFER6",0x882B);
    ADDVAR("DRAW_BUFFER7",0x882C);
    ADDVAR("DRAW_BUFFER8",0x882D);
    ADDVAR("DRAW_BUFFER9",0x882E);
    ADDVAR("DRAW_FRAMEBUFFER",0x8CA9);
    ADDVAR("DRAW_FRAMEBUFFER_BINDING",0x8CA6);
    ADDVAR("DRAW_INDIRECT_BUFFER",0x8F3F);
    ADDVAR("DRAW_INDIRECT_BUFFER_BINDING",0x8F43);
    ADDVAR("DST_ALPHA",0x0304);
    ADDVAR("DST_COLOR",0x0306);
    ADDVAR("DYNAMIC_COPY",0x88EA);
    ADDVAR("DYNAMIC_DRAW",0x88E8);
    ADDVAR("DYNAMIC_READ",0x88E9);
    ADDVAR("DYNAMIC_STORAGE_BIT",0x0100);
    ADDVAR("ELEMENT_ARRAY_BARRIER_BIT",0x00000002);
    ADDVAR("ELEMENT_ARRAY_BUFFER",0x8893);
    ADDVAR("ELEMENT_ARRAY_BUFFER_BINDING",0x8895);
    ADDVAR("EQUAL",0x0202);
    ADDVAR("EQUIV",0x1509);
    ADDVAR("EXTENSIONS",0x1F03);
    ADDVAR("FALSE",0);
    ADDVAR("FASTEST",0x1101);
    ADDVAR("FILL",0x1B02);
    ADDVAR("FILTER",0x829A);
    ADDVAR("FIRST_VERTEX_CONVENTION",0x8E4D);
    ADDVAR("FIXED",0x140C);
    ADDVAR("FIXED_ONLY",0x891D);
    ADDVAR("FLOAT",0x1406);
    ADDVAR("FLOAT_32_UNSIGNED_INT_24_8_REV",0x8DAD);
    ADDVAR("FLOAT_MAT2",0x8B5A);
    ADDVAR("FLOAT_MAT2x3",0x8B65);
    ADDVAR("FLOAT_MAT2x4",0x8B66);
    ADDVAR("FLOAT_MAT3",0x8B5B);
    ADDVAR("FLOAT_MAT3x2",0x8B67);
    ADDVAR("FLOAT_MAT3x4",0x8B68);
    ADDVAR("FLOAT_MAT4",0x8B5C);
    ADDVAR("FLOAT_MAT4x2",0x8B69);
    ADDVAR("FLOAT_MAT4x3",0x8B6A);
    ADDVAR("FLOAT_VEC2",0x8B50);
    ADDVAR("FLOAT_VEC3",0x8B51);
    ADDVAR("FLOAT_VEC4",0x8B52);
    ADDVAR("FRACTIONAL_EVEN",0x8E7C);
    ADDVAR("FRACTIONAL_ODD",0x8E7B);
    ADDVAR("FRAGMENT_INTERPOLATION_OFFSET_BITS",0x8E5D);
    ADDVAR("FRAGMENT_SHADER",0x8B30);
    ADDVAR("FRAGMENT_SHADER_BIT",0x00000002);
    ADDVAR("FRAGMENT_SHADER_DERIVATIVE_HINT",0x8B8B);
    ADDVAR("FRAGMENT_SUBROUTINE",0x92EC);
    ADDVAR("FRAGMENT_SUBROUTINE_UNIFORM",0x92F2);
    ADDVAR("FRAGMENT_TEXTURE",0x829F);
    ADDVAR("FRAMEBUFFER",0x8D40);
    ADDVAR("FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE",0x8215);
    ADDVAR("FRAMEBUFFER_ATTACHMENT_BLUE_SIZE",0x8214);
    ADDVAR("FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING",0x8210);
    ADDVAR("FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE",0x8211);
    ADDVAR("FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE",0x8216);
    ADDVAR("FRAMEBUFFER_ATTACHMENT_GREEN_SIZE",0x8213);
    ADDVAR("FRAMEBUFFER_ATTACHMENT_LAYERED",0x8DA7);
    ADDVAR("FRAMEBUFFER_ATTACHMENT_OBJECT_NAME",0x8CD1);
    ADDVAR("FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE",0x8CD0);
    ADDVAR("FRAMEBUFFER_ATTACHMENT_RED_SIZE",0x8212);
    ADDVAR("FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE",0x8217);
    ADDVAR("FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE",0x8CD3);
    ADDVAR("FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER",0x8CD4);
    ADDVAR("FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL",0x8CD2);
    ADDVAR("FRAMEBUFFER_BARRIER_BIT",0x00000400);
    ADDVAR("FRAMEBUFFER_BINDING",0x8CA6);
    ADDVAR("FRAMEBUFFER_BLEND",0x828B);
    ADDVAR("FRAMEBUFFER_COMPLETE",0x8CD5);
    ADDVAR("FRAMEBUFFER_DEFAULT",0x8218);
    ADDVAR("FRAMEBUFFER_DEFAULT_FIXED_SAMPLE_LOCATIONS",0x9314);
    ADDVAR("FRAMEBUFFER_DEFAULT_HEIGHT",0x9311);
    ADDVAR("FRAMEBUFFER_DEFAULT_LAYERS",0x9312);
    ADDVAR("FRAMEBUFFER_DEFAULT_SAMPLES",0x9313);
    ADDVAR("FRAMEBUFFER_DEFAULT_WIDTH",0x9310);
    ADDVAR("FRAMEBUFFER_INCOMPLETE_ATTACHMENT",0x8CD6);
    ADDVAR("FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER",0x8CDB);
    ADDVAR("FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS",0x8DA8);
    ADDVAR("FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT",0x8CD7);
    ADDVAR("FRAMEBUFFER_INCOMPLETE_MULTISAMPLE",0x8D56);
    ADDVAR("FRAMEBUFFER_INCOMPLETE_READ_BUFFER",0x8CDC);
    ADDVAR("FRAMEBUFFER_RENDERABLE",0x8289);
    ADDVAR("FRAMEBUFFER_RENDERABLE_LAYERED",0x828A);
    ADDVAR("FRAMEBUFFER_SRGB",0x8DB9);
    ADDVAR("FRAMEBUFFER_UNDEFINED",0x8219);
    ADDVAR("FRAMEBUFFER_UNSUPPORTED",0x8CDD);
    ADDVAR("FRONT",0x0404);
    ADDVAR("FRONT_AND_BACK",0x0408);
    ADDVAR("FRONT_FACE",0x0B46);
    ADDVAR("FRONT_LEFT",0x0400);
    ADDVAR("FRONT_RIGHT",0x0401);
    ADDVAR("FULL_SUPPORT",0x82B7);
    ADDVAR("FUNC_ADD",0x8006);
    ADDVAR("FUNC_REVERSE_SUBTRACT",0x800B);
    ADDVAR("FUNC_SUBTRACT",0x800A);
    ADDVAR("GEOMETRY_INPUT_TYPE",0x8917);
    ADDVAR("GEOMETRY_OUTPUT_TYPE",0x8918);
    ADDVAR("GEOMETRY_SHADER",0x8DD9);
    ADDVAR("GEOMETRY_SHADER_BIT",0x00000004);
    ADDVAR("GEOMETRY_SHADER_INVOCATIONS",0x887F);
    ADDVAR("GEOMETRY_SUBROUTINE",0x92EB);
    ADDVAR("GEOMETRY_SUBROUTINE_UNIFORM",0x92F1);
    ADDVAR("GEOMETRY_TEXTURE",0x829E);
    ADDVAR("GEOMETRY_VERTICES_OUT",0x8916);
    ADDVAR("GEQUAL",0x0206);
    ADDVAR("GET_TEXTURE_IMAGE_FORMAT",0x8291);
    ADDVAR("GET_TEXTURE_IMAGE_TYPE",0x8292);
    ADDVAR("GREATER",0x0204);
    ADDVAR("GREEN",0x1904);
    ADDVAR("GREEN_INTEGER",0x8D95);
    ADDVAR("HALF_FLOAT",0x140B);
    ADDVAR("HIGH_FLOAT",0x8DF2);
    ADDVAR("HIGH_INT",0x8DF5);
    ADDVAR("IMAGE_1D",0x904C);
    ADDVAR("IMAGE_1D_ARRAY",0x9052);
    ADDVAR("IMAGE_2D",0x904D);
    ADDVAR("IMAGE_2D_ARRAY",0x9053);
    ADDVAR("IMAGE_2D_MULTISAMPLE",0x9055);
    ADDVAR("IMAGE_2D_MULTISAMPLE_ARRAY",0x9056);
    ADDVAR("IMAGE_2D_RECT",0x904F);
    ADDVAR("IMAGE_3D",0x904E);
    ADDVAR("IMAGE_BINDING_ACCESS",0x8F3E);
    ADDVAR("IMAGE_BINDING_FORMAT",0x906E);
    ADDVAR("IMAGE_BINDING_LAYER",0x8F3D);
    ADDVAR("IMAGE_BINDING_LAYERED",0x8F3C);
    ADDVAR("IMAGE_BINDING_LEVEL",0x8F3B);
    ADDVAR("IMAGE_BINDING_NAME",0x8F3A);
    ADDVAR("IMAGE_BUFFER",0x9051);
    ADDVAR("IMAGE_CLASS_1_X_16",0x82BE);
    ADDVAR("IMAGE_CLASS_1_X_32",0x82BB);
    ADDVAR("IMAGE_CLASS_1_X_8",0x82C1);
    ADDVAR("IMAGE_CLASS_10_10_10_2",0x82C3);
    ADDVAR("IMAGE_CLASS_11_11_10",0x82C2);
    ADDVAR("IMAGE_CLASS_2_X_16",0x82BD);
    ADDVAR("IMAGE_CLASS_2_X_32",0x82BA);
    ADDVAR("IMAGE_CLASS_2_X_8",0x82C0);
    ADDVAR("IMAGE_CLASS_4_X_16",0x82BC);
    ADDVAR("IMAGE_CLASS_4_X_32",0x82B9);
    ADDVAR("IMAGE_CLASS_4_X_8",0x82BF);
    ADDVAR("IMAGE_COMPATIBILITY_CLASS",0x82A8);
    ADDVAR("IMAGE_CUBE",0x9050);
    ADDVAR("IMAGE_CUBE_MAP_ARRAY",0x9054);
    ADDVAR("IMAGE_FORMAT_COMPATIBILITY_BY_CLASS",0x90C9);
    ADDVAR("IMAGE_FORMAT_COMPATIBILITY_BY_SIZE",0x90C8);
    ADDVAR("IMAGE_FORMAT_COMPATIBILITY_TYPE",0x90C7);
    ADDVAR("IMAGE_PIXEL_FORMAT",0x82A9);
    ADDVAR("IMAGE_PIXEL_TYPE",0x82AA);
    ADDVAR("IMAGE_TEXEL_SIZE",0x82A7);
    ADDVAR("IMPLEMENTATION_COLOR_READ_FORMAT",0x8B9B);
    ADDVAR("IMPLEMENTATION_COLOR_READ_TYPE",0x8B9A);
    ADDVAR("INCR",0x1E02);
    ADDVAR("INCR_WRAP",0x8507);
    ADDVAR("INFO_LOG_LENGTH",0x8B84);
    ADDVAR("INT",0x1404);
    ADDVAR("INT_2_10_10_10_REV",0x8D9F);
    ADDVAR("INT_IMAGE_1D",0x9057);
    ADDVAR("INT_IMAGE_1D_ARRAY",0x905D);
    ADDVAR("INT_IMAGE_2D",0x9058);
    ADDVAR("INT_IMAGE_2D_ARRAY",0x905E);
    ADDVAR("INT_IMAGE_2D_MULTISAMPLE",0x9060);
    ADDVAR("INT_IMAGE_2D_MULTISAMPLE_ARRAY",0x9061);
    ADDVAR("INT_IMAGE_2D_RECT",0x905A);
    ADDVAR("INT_IMAGE_3D",0x9059);
    ADDVAR("INT_IMAGE_BUFFER",0x905C);
    ADDVAR("INT_IMAGE_CUBE",0x905B);
    ADDVAR("INT_IMAGE_CUBE_MAP_ARRAY",0x905F);
    ADDVAR("INT_SAMPLER_1D",0x8DC9);
    ADDVAR("INT_SAMPLER_1D_ARRAY",0x8DCE);
    ADDVAR("INT_SAMPLER_2D",0x8DCA);
    ADDVAR("INT_SAMPLER_2D_ARRAY",0x8DCF);
    ADDVAR("INT_SAMPLER_2D_MULTISAMPLE",0x9109);
    ADDVAR("INT_SAMPLER_2D_MULTISAMPLE_ARRAY",0x910C);
    ADDVAR("INT_SAMPLER_2D_RECT",0x8DCD);
    ADDVAR("INT_SAMPLER_3D",0x8DCB);
    ADDVAR("INT_SAMPLER_BUFFER",0x8DD0);
    ADDVAR("INT_SAMPLER_CUBE",0x8DCC);
    ADDVAR("INT_SAMPLER_CUBE_MAP_ARRAY",0x900E);
    ADDVAR("INT_VEC2",0x8B53);
    ADDVAR("INT_VEC3",0x8B54);
    ADDVAR("INT_VEC4",0x8B55);
    ADDVAR("INTERLEAVED_ATTRIBS",0x8C8C);
    ADDVAR("INTERNALFORMAT_ALPHA_SIZE",0x8274);
    ADDVAR("INTERNALFORMAT_ALPHA_TYPE",0x827B);
    ADDVAR("INTERNALFORMAT_BLUE_SIZE",0x8273);
    ADDVAR("INTERNALFORMAT_BLUE_TYPE",0x827A);
    ADDVAR("INTERNALFORMAT_DEPTH_SIZE",0x8275);
    ADDVAR("INTERNALFORMAT_DEPTH_TYPE",0x827C);
    ADDVAR("INTERNALFORMAT_GREEN_SIZE",0x8272);
    ADDVAR("INTERNALFORMAT_GREEN_TYPE",0x8279);
    ADDVAR("INTERNALFORMAT_PREFERRED",0x8270);
    ADDVAR("INTERNALFORMAT_RED_SIZE",0x8271);
    ADDVAR("INTERNALFORMAT_RED_TYPE",0x8278);
    ADDVAR("INTERNALFORMAT_SHARED_SIZE",0x8277);
    ADDVAR("INTERNALFORMAT_STENCIL_SIZE",0x8276);
    ADDVAR("INTERNALFORMAT_STENCIL_TYPE",0x827D);
    ADDVAR("INTERNALFORMAT_SUPPORTED",0x826F);
    ADDVAR("INVALID_ENUM",0x0500);
    ADDVAR("INVALID_FRAMEBUFFER_OPERATION",0x0506);
    ADDVAR("INVALID_INDEX",0xFFFFFFFFu);
    ADDVAR("INVALID_OPERATION",0x0502);
    ADDVAR("INVALID_VALUE",0x0501);
    ADDVAR("INVERT",0x150A);
    ADDVAR("IS_PER_PATCH",0x92E7);
    ADDVAR("IS_ROW_MAJOR",0x9300);
    ADDVAR("ISOLINES",0x8E7A);
    ADDVAR("KEEP",0x1E00);
    ADDVAR("LAST_VERTEX_CONVENTION",0x8E4E);
    ADDVAR("LAYER_PROVOKING_VERTEX",0x825E);
    ADDVAR("LEFT",0x0406);
    ADDVAR("LEQUAL",0x0203);
    ADDVAR("LESS",0x0201);
    ADDVAR("LINE",0x1B01);
    ADDVAR("LINE_LOOP",0x0002);
    ADDVAR("LINE_SMOOTH",0x0B20);
    ADDVAR("LINE_SMOOTH_HINT",0x0C52);
    ADDVAR("LINE_STRIP",0x0003);
    ADDVAR("LINE_STRIP_ADJACENCY",0x000B);
    ADDVAR("LINE_WIDTH",0x0B21);
    ADDVAR("LINE_WIDTH_GRANULARITY",0x0B23);
    ADDVAR("LINE_WIDTH_RANGE",0x0B22);
    ADDVAR("LINEAR",0x2601);
    ADDVAR("LINEAR_MIPMAP_LINEAR",0x2703);
    ADDVAR("LINEAR_MIPMAP_NEAREST",0x2701);
    ADDVAR("LINES",0x0001);
    ADDVAR("LINES_ADJACENCY",0x000A);
    ADDVAR("LINK_STATUS",0x8B82);
    ADDVAR("LOCATION",0x930E);
    ADDVAR("LOCATION_COMPONENT",0x934A);
    ADDVAR("LOCATION_INDEX",0x930F);
    ADDVAR("LOGIC_OP_MODE",0x0BF0);
    ADDVAR("LOW_FLOAT",0x8DF0);
    ADDVAR("LOW_INT",0x8DF3);
    ADDVAR("LOWER_LEFT",0x8CA1);
    ADDVAR("MAJOR_VERSION",0x821B);
    ADDVAR("MANUAL_GENERATE_MIPMAP",0x8294);
    ADDVAR("MAP_COHERENT_BIT",0x0080);
    ADDVAR("MAP_FLUSH_EXPLICIT_BIT",0x0010);
    ADDVAR("MAP_INVALIDATE_BUFFER_BIT",0x0008);
    ADDVAR("MAP_INVALIDATE_RANGE_BIT",0x0004);
    ADDVAR("MAP_PERSISTENT_BIT",0x0040);
    ADDVAR("MAP_READ_BIT",0x0001);
    ADDVAR("MAP_UNSYNCHRONIZED_BIT",0x0020);
    ADDVAR("MAP_WRITE_BIT",0x0002);
    ADDVAR("MATRIX_STRIDE",0x92FF);
    ADDVAR("MAX",0x8008);
    ADDVAR("MAX_3D_TEXTURE_SIZE",0x8073);
    ADDVAR("MAX_ARRAY_TEXTURE_LAYERS",0x88FF);
    ADDVAR("MAX_ATOMIC_COUNTER_BUFFER_BINDINGS",0x92DC);
    ADDVAR("MAX_ATOMIC_COUNTER_BUFFER_SIZE",0x92D8);
    ADDVAR("MAX_CLIP_DISTANCES",0x0D32);
    ADDVAR("MAX_COLOR_ATTACHMENTS",0x8CDF);
    ADDVAR("MAX_COLOR_TEXTURE_SAMPLES",0x910E);
    ADDVAR("MAX_COMBINED_ATOMIC_COUNTER_BUFFERS",0x92D1);
    ADDVAR("MAX_COMBINED_ATOMIC_COUNTERS",0x92D7);
    ADDVAR("MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS",0x8266);
    ADDVAR("MAX_COMBINED_DIMENSIONS",0x8282);
    ADDVAR("MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS",0x8A33);
    ADDVAR("MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS",0x8A32);
    ADDVAR("MAX_COMBINED_IMAGE_UNIFORMS",0x90CF);
    ADDVAR("MAX_COMBINED_IMAGE_UNITS_AND_FRAGMENT_OUTPUTS",0x8F39);
    ADDVAR("MAX_COMBINED_SHADER_OUTPUT_RESOURCES",0x8F39);
    ADDVAR("MAX_COMBINED_SHADER_STORAGE_BLOCKS",0x90DC);
    ADDVAR("MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS",0x8E1E);
    ADDVAR("MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS",0x8E1F);
    ADDVAR("MAX_COMBINED_TEXTURE_IMAGE_UNITS",0x8B4D);
    ADDVAR("MAX_COMBINED_UNIFORM_BLOCKS",0x8A2E);
    ADDVAR("MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS",0x8A31);
    ADDVAR("MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS",0x8264);
    ADDVAR("MAX_COMPUTE_ATOMIC_COUNTERS",0x8265);
    ADDVAR("MAX_COMPUTE_IMAGE_UNIFORMS",0x91BD);
    ADDVAR("MAX_COMPUTE_SHADER_STORAGE_BLOCKS",0x90DB);
    ADDVAR("MAX_COMPUTE_SHARED_MEMORY_SIZE",0x8262);
    ADDVAR("MAX_COMPUTE_TEXTURE_IMAGE_UNITS",0x91BC);
    ADDVAR("MAX_COMPUTE_UNIFORM_BLOCKS",0x91BB);
    ADDVAR("MAX_COMPUTE_UNIFORM_COMPONENTS",0x8263);
    ADDVAR("MAX_COMPUTE_WORK_GROUP_COUNT",0x91BE);
    ADDVAR("MAX_COMPUTE_WORK_GROUP_INVOCATIONS",0x90EB);
    ADDVAR("MAX_COMPUTE_WORK_GROUP_SIZE",0x91BF);
    ADDVAR("MAX_CUBE_MAP_TEXTURE_SIZE",0x851C);
    ADDVAR("MAX_DEBUG_GROUP_STACK_DEPTH",0x826C);
    ADDVAR("MAX_DEBUG_LOGGED_MESSAGES",0x9144);
    ADDVAR("MAX_DEBUG_MESSAGE_LENGTH",0x9143);
    ADDVAR("MAX_DEPTH",0x8280);
    ADDVAR("MAX_DEPTH_TEXTURE_SAMPLES",0x910F);
    ADDVAR("MAX_DRAW_BUFFERS",0x8824);
    ADDVAR("MAX_DUAL_SOURCE_DRAW_BUFFERS",0x88FC);
    ADDVAR("MAX_ELEMENT_INDEX",0x8D6B);
    ADDVAR("MAX_ELEMENTS_INDICES",0x80E9);
    ADDVAR("MAX_ELEMENTS_VERTICES",0x80E8);
    ADDVAR("MAX_FRAGMENT_ATOMIC_COUNTER_BUFFERS",0x92D0);
    ADDVAR("MAX_FRAGMENT_ATOMIC_COUNTERS",0x92D6);
    ADDVAR("MAX_FRAGMENT_IMAGE_UNIFORMS",0x90CE);
    ADDVAR("MAX_FRAGMENT_INPUT_COMPONENTS",0x9125);
    ADDVAR("MAX_FRAGMENT_INTERPOLATION_OFFSET",0x8E5C);
    ADDVAR("MAX_FRAGMENT_SHADER_STORAGE_BLOCKS",0x90DA);
    ADDVAR("MAX_FRAGMENT_UNIFORM_BLOCKS",0x8A2D);
    ADDVAR("MAX_FRAGMENT_UNIFORM_COMPONENTS",0x8B49);
    ADDVAR("MAX_FRAGMENT_UNIFORM_VECTORS",0x8DFD);
    ADDVAR("MAX_FRAMEBUFFER_HEIGHT",0x9316);
    ADDVAR("MAX_FRAMEBUFFER_LAYERS",0x9317);
    ADDVAR("MAX_FRAMEBUFFER_SAMPLES",0x9318);
    ADDVAR("MAX_FRAMEBUFFER_WIDTH",0x9315);
    ADDVAR("MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS",0x92CF);
    ADDVAR("MAX_GEOMETRY_ATOMIC_COUNTERS",0x92D5);
    ADDVAR("MAX_GEOMETRY_IMAGE_UNIFORMS",0x90CD);
    ADDVAR("MAX_GEOMETRY_INPUT_COMPONENTS",0x9123);
    ADDVAR("MAX_GEOMETRY_OUTPUT_COMPONENTS",0x9124);
    ADDVAR("MAX_GEOMETRY_OUTPUT_VERTICES",0x8DE0);
    ADDVAR("MAX_GEOMETRY_SHADER_INVOCATIONS",0x8E5A);
    ADDVAR("MAX_GEOMETRY_SHADER_STORAGE_BLOCKS",0x90D7);
    ADDVAR("MAX_GEOMETRY_TEXTURE_IMAGE_UNITS",0x8C29);
    ADDVAR("MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS",0x8DE1);
    ADDVAR("MAX_GEOMETRY_UNIFORM_BLOCKS",0x8A2C);
    ADDVAR("MAX_GEOMETRY_UNIFORM_COMPONENTS",0x8DDF);
    ADDVAR("MAX_HEIGHT",0x827F);
    ADDVAR("MAX_IMAGE_SAMPLES",0x906D);
    ADDVAR("MAX_IMAGE_UNITS",0x8F38);
    ADDVAR("MAX_INTEGER_SAMPLES",0x9110);
    ADDVAR("MAX_LABEL_LENGTH",0x82E8);
    ADDVAR("MAX_LAYERS",0x8281);
    ADDVAR("MAX_NAME_LENGTH",0x92F6);
    ADDVAR("MAX_NUM_ACTIVE_VARIABLES",0x92F7);
    ADDVAR("MAX_NUM_COMPATIBLE_SUBROUTINES",0x92F8);
    ADDVAR("MAX_PATCH_VERTICES",0x8E7D);
    ADDVAR("MAX_PROGRAM_TEXEL_OFFSET",0x8905);
    ADDVAR("MAX_PROGRAM_TEXTURE_GATHER_OFFSET",0x8E5F);
    ADDVAR("MAX_RECTANGLE_TEXTURE_SIZE",0x84F8);
    ADDVAR("MAX_RENDERBUFFER_SIZE",0x84E8);
    ADDVAR("MAX_SAMPLE_MASK_WORDS",0x8E59);
    ADDVAR("MAX_SAMPLES",0x8D57);
    ADDVAR("MAX_SERVER_WAIT_TIMEOUT",0x9111);
    ADDVAR("MAX_SHADER_STORAGE_BLOCK_SIZE",0x90DE);
    ADDVAR("MAX_SHADER_STORAGE_BUFFER_BINDINGS",0x90DD);
    ADDVAR("MAX_SUBROUTINE_UNIFORM_LOCATIONS",0x8DE8);
    ADDVAR("MAX_SUBROUTINES",0x8DE7);
    ADDVAR("MAX_TESS_CONTROL_ATOMIC_COUNTER_BUFFERS",0x92CD);
    ADDVAR("MAX_TESS_CONTROL_ATOMIC_COUNTERS",0x92D3);
    ADDVAR("MAX_TESS_CONTROL_IMAGE_UNIFORMS",0x90CB);
    ADDVAR("MAX_TESS_CONTROL_INPUT_COMPONENTS",0x886C);
    ADDVAR("MAX_TESS_CONTROL_OUTPUT_COMPONENTS",0x8E83);
    ADDVAR("MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS",0x90D8);
    ADDVAR("MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS",0x8E81);
    ADDVAR("MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS",0x8E85);
    ADDVAR("MAX_TESS_CONTROL_UNIFORM_BLOCKS",0x8E89);
    ADDVAR("MAX_TESS_CONTROL_UNIFORM_COMPONENTS",0x8E7F);
    ADDVAR("MAX_TESS_EVALUATION_ATOMIC_COUNTER_BUFFERS",0x92CE);
    ADDVAR("MAX_TESS_EVALUATION_ATOMIC_COUNTERS",0x92D4);
    ADDVAR("MAX_TESS_EVALUATION_IMAGE_UNIFORMS",0x90CC);
    ADDVAR("MAX_TESS_EVALUATION_INPUT_COMPONENTS",0x886D);
    ADDVAR("MAX_TESS_EVALUATION_OUTPUT_COMPONENTS",0x8E86);
    ADDVAR("MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS",0x90D9);
    ADDVAR("MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS",0x8E82);
    ADDVAR("MAX_TESS_EVALUATION_UNIFORM_BLOCKS",0x8E8A);
    ADDVAR("MAX_TESS_EVALUATION_UNIFORM_COMPONENTS",0x8E80);
    ADDVAR("MAX_TESS_GEN_LEVEL",0x8E7E);
    ADDVAR("MAX_TESS_PATCH_COMPONENTS",0x8E84);
    ADDVAR("MAX_TEXTURE_BUFFER_SIZE",0x8C2B);
    ADDVAR("MAX_TEXTURE_IMAGE_UNITS",0x8872);
    ADDVAR("MAX_TEXTURE_LOD_BIAS",0x84FD);
    ADDVAR("MAX_TEXTURE_SIZE",0x0D33);
    ADDVAR("MAX_TRANSFORM_FEEDBACK_BUFFERS",0x8E70);
    ADDVAR("MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS",0x8C8A);
    ADDVAR("MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS",0x8C8B);
    ADDVAR("MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS",0x8C80);
    ADDVAR("MAX_UNIFORM_BLOCK_SIZE",0x8A30);
    ADDVAR("MAX_UNIFORM_BUFFER_BINDINGS",0x8A2F);
    ADDVAR("MAX_UNIFORM_LOCATIONS",0x826E);
    ADDVAR("MAX_VARYING_COMPONENTS",0x8B4B);
    ADDVAR("MAX_VARYING_FLOATS",0x8B4B);
    ADDVAR("MAX_VARYING_VECTORS",0x8DFC);
    ADDVAR("MAX_VERTEX_ATOMIC_COUNTER_BUFFERS",0x92CC);
    ADDVAR("MAX_VERTEX_ATOMIC_COUNTERS",0x92D2);
    ADDVAR("MAX_VERTEX_ATTRIB_BINDINGS",0x82DA);
    ADDVAR("MAX_VERTEX_ATTRIB_RELATIVE_OFFSET",0x82D9);
    ADDVAR("MAX_VERTEX_ATTRIB_STRIDE",0x82E5);
    ADDVAR("MAX_VERTEX_ATTRIBS",0x8869);
    ADDVAR("MAX_VERTEX_IMAGE_UNIFORMS",0x90CA);
    ADDVAR("MAX_VERTEX_OUTPUT_COMPONENTS",0x9122);
    ADDVAR("MAX_VERTEX_SHADER_STORAGE_BLOCKS",0x90D6);
    ADDVAR("MAX_VERTEX_STREAMS",0x8E71);
    ADDVAR("MAX_VERTEX_TEXTURE_IMAGE_UNITS",0x8B4C);
    ADDVAR("MAX_VERTEX_UNIFORM_BLOCKS",0x8A2B);
    ADDVAR("MAX_VERTEX_UNIFORM_COMPONENTS",0x8B4A);
    ADDVAR("MAX_VERTEX_UNIFORM_VECTORS",0x8DFB);
    ADDVAR("MAX_VIEWPORT_DIMS",0x0D3A);
    ADDVAR("MAX_VIEWPORTS",0x825B);
    ADDVAR("MAX_WIDTH",0x827E);
    ADDVAR("MEDIUM_FLOAT",0x8DF1);
    ADDVAR("MEDIUM_INT",0x8DF4);
    ADDVAR("MIN",0x8007);
    ADDVAR("MIN_FRAGMENT_INTERPOLATION_OFFSET",0x8E5B);
    ADDVAR("MIN_MAP_BUFFER_ALIGNMENT",0x90BC);
    ADDVAR("MIN_PROGRAM_TEXEL_OFFSET",0x8904);
    ADDVAR("MIN_PROGRAM_TEXTURE_GATHER_OFFSET",0x8E5E);
    ADDVAR("MIN_SAMPLE_SHADING_VALUE",0x8C37);
    ADDVAR("MINOR_VERSION",0x821C);
    ADDVAR("MIPMAP",0x8293);
    ADDVAR("MIRROR_CLAMP_TO_EDGE",0x8743);
    ADDVAR("MIRRORED_REPEAT",0x8370);
    ADDVAR("MULTISAMPLE",0x809D);
    ADDVAR("NAME_LENGTH",0x92F9);
    ADDVAR("NAND",0x150E);
    ADDVAR("NEAREST",0x2600);
    ADDVAR("NEAREST_MIPMAP_LINEAR",0x2702);
    ADDVAR("NEAREST_MIPMAP_NEAREST",0x2700);
    ADDVAR("NEVER",0x0200);
    ADDVAR("NICEST",0x1102);
    ADDVAR("NO_ERROR",0);
    ADDVAR("NONE",0);
    ADDVAR("NOOP",0x1505);
    ADDVAR("NOR",0x1508);
    ADDVAR("NOTEQUAL",0x0205);
    ADDVAR("NUM_ACTIVE_VARIABLES",0x9304);
    ADDVAR("NUM_COMPATIBLE_SUBROUTINES",0x8E4A);
    ADDVAR("NUM_COMPRESSED_TEXTURE_FORMATS",0x86A2);
    ADDVAR("NUM_EXTENSIONS",0x821D);
    ADDVAR("NUM_PROGRAM_BINARY_FORMATS",0x87FE);
    ADDVAR("NUM_SAMPLE_COUNTS",0x9380);
    ADDVAR("NUM_SHADER_BINARY_FORMATS",0x8DF9);
    ADDVAR("NUM_SHADING_LANGUAGE_VERSIONS",0x82E9);
    ADDVAR("OBJECT_TYPE",0x9112);
    ADDVAR("OFFSET",0x92FC);
    ADDVAR("ONE",1);
    ADDVAR("ONE_MINUS_CONSTANT_ALPHA",0x8004);
    ADDVAR("ONE_MINUS_CONSTANT_COLOR",0x8002);
    ADDVAR("ONE_MINUS_DST_ALPHA",0x0305);
    ADDVAR("ONE_MINUS_DST_COLOR",0x0307);
    ADDVAR("ONE_MINUS_SRC_ALPHA",0x0303);
    ADDVAR("ONE_MINUS_SRC_COLOR",0x0301);
    ADDVAR("ONE_MINUS_SRC1_ALPHA",0x88FB);
    ADDVAR("ONE_MINUS_SRC1_COLOR",0x88FA);
    ADDVAR("OR",0x1507);
    ADDVAR("OR_INVERTED",0x150D);
    ADDVAR("OR_REVERSE",0x150B);
    ADDVAR("OUT_OF_MEMORY",0x0505);
    ADDVAR("PACK_ALIGNMENT",0x0D05);
    ADDVAR("PACK_COMPRESSED_BLOCK_DEPTH",0x912D);
    ADDVAR("PACK_COMPRESSED_BLOCK_HEIGHT",0x912C);
    ADDVAR("PACK_COMPRESSED_BLOCK_SIZE",0x912E);
    ADDVAR("PACK_COMPRESSED_BLOCK_WIDTH",0x912B);
    ADDVAR("PACK_IMAGE_HEIGHT",0x806C);
    ADDVAR("PACK_LSB_FIRST",0x0D01);
    ADDVAR("PACK_ROW_LENGTH",0x0D02);
    ADDVAR("PACK_SKIP_IMAGES",0x806B);
    ADDVAR("PACK_SKIP_PIXELS",0x0D04);
    ADDVAR("PACK_SKIP_ROWS",0x0D03);
    ADDVAR("PACK_SWAP_BYTES",0x0D00);
    ADDVAR("PATCH_DEFAULT_INNER_LEVEL",0x8E73);
    ADDVAR("PATCH_DEFAULT_OUTER_LEVEL",0x8E74);
    ADDVAR("PATCH_VERTICES",0x8E72);
    ADDVAR("PATCHES",0x000E);
    ADDVAR("PIXEL_BUFFER_BARRIER_BIT",0x00000080);
    ADDVAR("PIXEL_PACK_BUFFER",0x88EB);
    ADDVAR("PIXEL_PACK_BUFFER_BINDING",0x88ED);
    ADDVAR("PIXEL_UNPACK_BUFFER",0x88EC);
    ADDVAR("PIXEL_UNPACK_BUFFER_BINDING",0x88EF);
    ADDVAR("POINT",0x1B00);
    ADDVAR("POINT_FADE_THRESHOLD_SIZE",0x8128);
    ADDVAR("POINT_SIZE",0x0B11);
    ADDVAR("POINT_SIZE_GRANULARITY",0x0B13);
    ADDVAR("POINT_SIZE_RANGE",0x0B12);
    ADDVAR("POINT_SPRITE_COORD_ORIGIN",0x8CA0);
    ADDVAR("POINTS",0x0000);
    ADDVAR("POLYGON_MODE",0x0B40);
    ADDVAR("POLYGON_OFFSET_FACTOR",0x8038);
    ADDVAR("POLYGON_OFFSET_FILL",0x8037);
    ADDVAR("POLYGON_OFFSET_LINE",0x2A02);
    ADDVAR("POLYGON_OFFSET_POINT",0x2A01);
    ADDVAR("POLYGON_OFFSET_UNITS",0x2A00);
    ADDVAR("POLYGON_SMOOTH",0x0B41);
    ADDVAR("POLYGON_SMOOTH_HINT",0x0C53);
    ADDVAR("PRIMITIVE_RESTART",0x8F9D);
    ADDVAR("PRIMITIVE_RESTART_FIXED_INDEX",0x8D69);
    ADDVAR("PRIMITIVE_RESTART_FOR_PATCHES_SUPPORTED",0x8221);
    ADDVAR("PRIMITIVE_RESTART_INDEX",0x8F9E);
    ADDVAR("PRIMITIVES_GENERATED",0x8C87);
    ADDVAR("PROGRAM",0x82E2);
    ADDVAR("PROGRAM_BINARY_FORMATS",0x87FF);
    ADDVAR("PROGRAM_BINARY_LENGTH",0x8741);
    ADDVAR("PROGRAM_BINARY_RETRIEVABLE_HINT",0x8257);
    ADDVAR("PROGRAM_INPUT",0x92E3);
    ADDVAR("PROGRAM_OUTPUT",0x92E4);
    ADDVAR("PROGRAM_PIPELINE",0x82E4);
    ADDVAR("PROGRAM_PIPELINE_BINDING",0x825A);
    ADDVAR("PROGRAM_POINT_SIZE",0x8642);
    ADDVAR("PROGRAM_SEPARABLE",0x8258);
    ADDVAR("PROVOKING_VERTEX",0x8E4F);
    ADDVAR("PROXY_TEXTURE_1D",0x8063);
    ADDVAR("PROXY_TEXTURE_1D_ARRAY",0x8C19);
    ADDVAR("PROXY_TEXTURE_2D",0x8064);
    ADDVAR("PROXY_TEXTURE_2D_ARRAY",0x8C1B);
    ADDVAR("PROXY_TEXTURE_2D_MULTISAMPLE",0x9101);
    ADDVAR("PROXY_TEXTURE_2D_MULTISAMPLE_ARRAY",0x9103);
    ADDVAR("PROXY_TEXTURE_3D",0x8070);
    ADDVAR("PROXY_TEXTURE_CUBE_MAP",0x851B);
    ADDVAR("PROXY_TEXTURE_CUBE_MAP_ARRAY",0x900B);
    ADDVAR("PROXY_TEXTURE_RECTANGLE",0x84F7);
    ADDVAR("QUADS",0x0007);
    ADDVAR("QUADS_FOLLOW_PROVOKING_VERTEX_CONVENTION",0x8E4C);
    ADDVAR("QUERY",0x82E3);
    ADDVAR("QUERY_BUFFER",0x9192);
    ADDVAR("QUERY_BUFFER_BARRIER_BIT",0x00008000);
    ADDVAR("QUERY_BUFFER_BINDING",0x9193);
    ADDVAR("QUERY_BY_REGION_NO_WAIT",0x8E16);
    ADDVAR("QUERY_BY_REGION_WAIT",0x8E15);
    ADDVAR("QUERY_COUNTER_BITS",0x8864);
    ADDVAR("QUERY_NO_WAIT",0x8E14);
    ADDVAR("QUERY_RESULT",0x8866);
    ADDVAR("QUERY_RESULT_AVAILABLE",0x8867);
    ADDVAR("QUERY_RESULT_NO_WAIT",0x9194);
    ADDVAR("QUERY_WAIT",0x8E13);
    ADDVAR("R11F_G11F_B10F",0x8C3A);
    ADDVAR("R16",0x822A);
    ADDVAR("R16_SNORM",0x8F98);
    ADDVAR("R16F",0x822D);
    ADDVAR("R16I",0x8233);
    ADDVAR("R16UI",0x8234);
    ADDVAR("R3_G3_B2",0x2A10);
    ADDVAR("R32F",0x822E);
    ADDVAR("R32I",0x8235);
    ADDVAR("R32UI",0x8236);
    ADDVAR("R8",0x8229);
    ADDVAR("R8_SNORM",0x8F94);
    ADDVAR("R8I",0x8231);
    ADDVAR("R8UI",0x8232);
    ADDVAR("RASTERIZER_DISCARD",0x8C89);
    ADDVAR("READ_BUFFER",0x0C02);
    ADDVAR("READ_FRAMEBUFFER",0x8CA8);
    ADDVAR("READ_FRAMEBUFFER_BINDING",0x8CAA);
    ADDVAR("READ_ONLY",0x88B8);
    ADDVAR("READ_PIXELS",0x828C);
    ADDVAR("READ_PIXELS_FORMAT",0x828D);
    ADDVAR("READ_PIXELS_TYPE",0x828E);
    ADDVAR("READ_WRITE",0x88BA);
    ADDVAR("RED",0x1903);
    ADDVAR("RED_INTEGER",0x8D94);
    ADDVAR("REFERENCED_BY_COMPUTE_SHADER",0x930B);
    ADDVAR("REFERENCED_BY_FRAGMENT_SHADER",0x930A);
    ADDVAR("REFERENCED_BY_GEOMETRY_SHADER",0x9309);
    ADDVAR("REFERENCED_BY_TESS_CONTROL_SHADER",0x9307);
    ADDVAR("REFERENCED_BY_TESS_EVALUATION_SHADER",0x9308);
    ADDVAR("REFERENCED_BY_VERTEX_SHADER",0x9306);
    ADDVAR("RENDERBUFFER",0x8D41);
    ADDVAR("RENDERBUFFER_ALPHA_SIZE",0x8D53);
    ADDVAR("RENDERBUFFER_BINDING",0x8CA7);
    ADDVAR("RENDERBUFFER_BLUE_SIZE",0x8D52);
    ADDVAR("RENDERBUFFER_DEPTH_SIZE",0x8D54);
    ADDVAR("RENDERBUFFER_GREEN_SIZE",0x8D51);
    ADDVAR("RENDERBUFFER_HEIGHT",0x8D43);
    ADDVAR("RENDERBUFFER_INTERNAL_FORMAT",0x8D44);
    ADDVAR("RENDERBUFFER_RED_SIZE",0x8D50);
    ADDVAR("RENDERBUFFER_SAMPLES",0x8CAB);
    ADDVAR("RENDERBUFFER_STENCIL_SIZE",0x8D55);
    ADDVAR("RENDERBUFFER_WIDTH",0x8D42);
    ADDVAR("RENDERER",0x1F01);
    ADDVAR("REPEAT",0x2901);
    ADDVAR("REPLACE",0x1E01);
    ADDVAR("RG",0x8227);
    ADDVAR("RG_INTEGER",0x8228);
    ADDVAR("RG16",0x822C);
    ADDVAR("RG16_SNORM",0x8F99);
    ADDVAR("RG16F",0x822F);
    ADDVAR("RG16I",0x8239);
    ADDVAR("RG16UI",0x823A);
    ADDVAR("RG32F",0x8230);
    ADDVAR("RG32I",0x823B);
    ADDVAR("RG32UI",0x823C);
    ADDVAR("RG8",0x822B);
    ADDVAR("RG8_SNORM",0x8F95);
    ADDVAR("RG8I",0x8237);
    ADDVAR("RG8UI",0x8238);
    ADDVAR("RGB",0x1907);
    ADDVAR("RGB_INTEGER",0x8D98);
    ADDVAR("RGB10",0x8052);
    ADDVAR("RGB10_A2",0x8059);
    ADDVAR("RGB10_A2UI",0x906F);
    ADDVAR("RGB12",0x8053);
    ADDVAR("RGB16",0x8054);
    ADDVAR("RGB16_SNORM",0x8F9A);
    ADDVAR("RGB16F",0x881B);
    ADDVAR("RGB16I",0x8D89);
    ADDVAR("RGB16UI",0x8D77);
    ADDVAR("RGB32F",0x8815);
    ADDVAR("RGB32I",0x8D83);
    ADDVAR("RGB32UI",0x8D71);
    ADDVAR("RGB4",0x804F);
    ADDVAR("RGB5",0x8050);
    ADDVAR("RGB5_A1",0x8057);
    ADDVAR("RGB565",0x8D62);
    ADDVAR("RGB8",0x8051);
    ADDVAR("RGB8_SNORM",0x8F96);
    ADDVAR("RGB8I",0x8D8F);
    ADDVAR("RGB8UI",0x8D7D);
    ADDVAR("RGB9_E5",0x8C3D);
    ADDVAR("RGBA",0x1908);
    ADDVAR("RGBA_INTEGER",0x8D99);
    ADDVAR("RGBA12",0x805A);
    ADDVAR("RGBA16",0x805B);
    ADDVAR("RGBA16_SNORM",0x8F9B);
    ADDVAR("RGBA16F",0x881A);
    ADDVAR("RGBA16I",0x8D88);
    ADDVAR("RGBA16UI",0x8D76);
    ADDVAR("RGBA2",0x8055);
    ADDVAR("RGBA32F",0x8814);
    ADDVAR("RGBA32I",0x8D82);
    ADDVAR("RGBA32UI",0x8D70);
    ADDVAR("RGBA4",0x8056);
    ADDVAR("RGBA8",0x8058);
    ADDVAR("RGBA8_SNORM",0x8F97);
    ADDVAR("RGBA8I",0x8D8E);
    ADDVAR("RGBA8UI",0x8D7C);
    ADDVAR("RIGHT",0x0407);
    ADDVAR("SAMPLE_ALPHA_TO_COVERAGE",0x809E);
    ADDVAR("SAMPLE_ALPHA_TO_ONE",0x809F);
    ADDVAR("SAMPLE_BUFFERS",0x80A8);
    ADDVAR("SAMPLE_COVERAGE",0x80A0);
    ADDVAR("SAMPLE_COVERAGE_INVERT",0x80AB);
    ADDVAR("SAMPLE_COVERAGE_VALUE",0x80AA);
    ADDVAR("SAMPLE_MASK",0x8E51);
    ADDVAR("SAMPLE_MASK_VALUE",0x8E52);
    ADDVAR("SAMPLE_POSITION",0x8E50);
    ADDVAR("SAMPLE_SHADING",0x8C36);
    ADDVAR("SAMPLER",0x82E6);
    ADDVAR("SAMPLER_1D",0x8B5D);
    ADDVAR("SAMPLER_1D_ARRAY",0x8DC0);
    ADDVAR("SAMPLER_1D_ARRAY_SHADOW",0x8DC3);
    ADDVAR("SAMPLER_1D_SHADOW",0x8B61);
    ADDVAR("SAMPLER_2D",0x8B5E);
    ADDVAR("SAMPLER_2D_ARRAY",0x8DC1);
    ADDVAR("SAMPLER_2D_ARRAY_SHADOW",0x8DC4);
    ADDVAR("SAMPLER_2D_MULTISAMPLE",0x9108);
    ADDVAR("SAMPLER_2D_MULTISAMPLE_ARRAY",0x910B);
    ADDVAR("SAMPLER_2D_RECT",0x8B63);
    ADDVAR("SAMPLER_2D_RECT_SHADOW",0x8B64);
    ADDVAR("SAMPLER_2D_SHADOW",0x8B62);
    ADDVAR("SAMPLER_3D",0x8B5F);
    ADDVAR("SAMPLER_BINDING",0x8919);
    ADDVAR("SAMPLER_BUFFER",0x8DC2);
    ADDVAR("SAMPLER_CUBE",0x8B60);
    ADDVAR("SAMPLER_CUBE_MAP_ARRAY",0x900C);
    ADDVAR("SAMPLER_CUBE_MAP_ARRAY_SHADOW",0x900D);
    ADDVAR("SAMPLER_CUBE_SHADOW",0x8DC5);
    ADDVAR("SAMPLES",0x80A9);
    ADDVAR("SAMPLES_PASSED",0x8914);
    ADDVAR("SCISSOR_BOX",0x0C10);
    ADDVAR("SCISSOR_TEST",0x0C11);
    ADDVAR("SEPARATE_ATTRIBS",0x8C8D);
    ADDVAR("SET",0x150F);
    ADDVAR("SHADER",0x82E1);
    ADDVAR("SHADER_BINARY_FORMATS",0x8DF8);
    ADDVAR("SHADER_COMPILER",0x8DFA);
    ADDVAR("SHADER_IMAGE_ACCESS_BARRIER_BIT",0x00000020);
    ADDVAR("SHADER_IMAGE_ATOMIC",0x82A6);
    ADDVAR("SHADER_IMAGE_LOAD",0x82A4);
    ADDVAR("SHADER_IMAGE_STORE",0x82A5);
    ADDVAR("SHADER_SOURCE_LENGTH",0x8B88);
    ADDVAR("SHADER_STORAGE_BARRIER_BIT",0x00002000);
    ADDVAR("SHADER_STORAGE_BLOCK",0x92E6);
    ADDVAR("SHADER_STORAGE_BUFFER",0x90D2);
    ADDVAR("SHADER_STORAGE_BUFFER_BINDING",0x90D3);
    ADDVAR("SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT",0x90DF);
    ADDVAR("SHADER_STORAGE_BUFFER_SIZE",0x90D5);
    ADDVAR("SHADER_STORAGE_BUFFER_START",0x90D4);
    ADDVAR("SHADER_TYPE",0x8B4F);
    ADDVAR("SHADING_LANGUAGE_VERSION",0x8B8C);
    ADDVAR("SHORT",0x1402);
    ADDVAR("SIGNALED",0x9119);
    ADDVAR("SIGNED_NORMALIZED",0x8F9C);
    ADDVAR("SIMULTANEOUS_TEXTURE_AND_DEPTH_TEST",0x82AC);
    ADDVAR("SIMULTANEOUS_TEXTURE_AND_DEPTH_WRITE",0x82AE);
    ADDVAR("SIMULTANEOUS_TEXTURE_AND_STENCIL_TEST",0x82AD);
    ADDVAR("SIMULTANEOUS_TEXTURE_AND_STENCIL_WRITE",0x82AF);
    ADDVAR("SMOOTH_LINE_WIDTH_GRANULARITY",0x0B23);
    ADDVAR("SMOOTH_LINE_WIDTH_RANGE",0x0B22);
    ADDVAR("SMOOTH_POINT_SIZE_GRANULARITY",0x0B13);
    ADDVAR("SMOOTH_POINT_SIZE_RANGE",0x0B12);
    ADDVAR("SRC_ALPHA",0x0302);
    ADDVAR("SRC_ALPHA_SATURATE",0x0308);
    ADDVAR("SRC_COLOR",0x0300);
    ADDVAR("SRC1_ALPHA",0x8589);
    ADDVAR("SRC1_COLOR",0x88F9);
    ADDVAR("SRGB",0x8C40);
    ADDVAR("SRGB_ALPHA",0x8C42);
    ADDVAR("SRGB_READ",0x8297);
    ADDVAR("SRGB_WRITE",0x8298);
    ADDVAR("SRGB8",0x8C41);
    ADDVAR("SRGB8_ALPHA8",0x8C43);
    ADDVAR("STACK_OVERFLOW",0x0503);
    ADDVAR("STACK_UNDERFLOW",0x0504);
    ADDVAR("STATIC_COPY",0x88E6);
    ADDVAR("STATIC_DRAW",0x88E4);
    ADDVAR("STATIC_READ",0x88E5);
    ADDVAR("STENCIL",0x1802);
    ADDVAR("STENCIL_ATTACHMENT",0x8D20);
    ADDVAR("STENCIL_BACK_FAIL",0x8801);
    ADDVAR("STENCIL_BACK_FUNC",0x8800);
    ADDVAR("STENCIL_BACK_PASS_DEPTH_FAIL",0x8802);
    ADDVAR("STENCIL_BACK_PASS_DEPTH_PASS",0x8803);
    ADDVAR("STENCIL_BACK_REF",0x8CA3);
    ADDVAR("STENCIL_BACK_VALUE_MASK",0x8CA4);
    ADDVAR("STENCIL_BACK_WRITEMASK",0x8CA5);
    ADDVAR("STENCIL_BUFFER_BIT",0x00000400);
    ADDVAR("STENCIL_CLEAR_VALUE",0x0B91);
    ADDVAR("STENCIL_COMPONENTS",0x8285);
    ADDVAR("STENCIL_FAIL",0x0B94);
    ADDVAR("STENCIL_FUNC",0x0B92);
    ADDVAR("STENCIL_INDEX",0x1901);
    ADDVAR("STENCIL_INDEX1",0x8D46);
    ADDVAR("STENCIL_INDEX16",0x8D49);
    ADDVAR("STENCIL_INDEX4",0x8D47);
    ADDVAR("STENCIL_INDEX8",0x8D48);
    ADDVAR("STENCIL_PASS_DEPTH_FAIL",0x0B95);
    ADDVAR("STENCIL_PASS_DEPTH_PASS",0x0B96);
    ADDVAR("STENCIL_REF",0x0B97);
    ADDVAR("STENCIL_RENDERABLE",0x8288);
    ADDVAR("STENCIL_TEST",0x0B90);
    ADDVAR("STENCIL_VALUE_MASK",0x0B93);
    ADDVAR("STENCIL_WRITEMASK",0x0B98);
    ADDVAR("STEREO",0x0C33);
    ADDVAR("STREAM_COPY",0x88E2);
    ADDVAR("STREAM_DRAW",0x88E0);
    ADDVAR("STREAM_READ",0x88E1);
    ADDVAR("SUBPIXEL_BITS",0x0D50);
    ADDVAR("SYNC_CONDITION",0x9113);
    ADDVAR("SYNC_FENCE",0x9116);
    ADDVAR("SYNC_FLAGS",0x9115);
    ADDVAR("SYNC_FLUSH_COMMANDS_BIT",0x00000001);
    ADDVAR("SYNC_GPU_COMMANDS_COMPLETE",0x9117);
    ADDVAR("SYNC_STATUS",0x9114);
    ADDVAR("TESS_CONTROL_OUTPUT_VERTICES",0x8E75);
    ADDVAR("TESS_CONTROL_SHADER",0x8E88);
    ADDVAR("TESS_CONTROL_SHADER_BIT",0x00000008);
    ADDVAR("TESS_CONTROL_SUBROUTINE",0x92E9);
    ADDVAR("TESS_CONTROL_SUBROUTINE_UNIFORM",0x92EF);
    ADDVAR("TESS_CONTROL_TEXTURE",0x829C);
    ADDVAR("TESS_EVALUATION_SHADER",0x8E87);
    ADDVAR("TESS_EVALUATION_SHADER_BIT",0x00000010);
    ADDVAR("TESS_EVALUATION_SUBROUTINE",0x92EA);
    ADDVAR("TESS_EVALUATION_SUBROUTINE_UNIFORM",0x92F0);
    ADDVAR("TESS_EVALUATION_TEXTURE",0x829D);
    ADDVAR("TESS_GEN_MODE",0x8E76);
    ADDVAR("TESS_GEN_POINT_MODE",0x8E79);
    ADDVAR("TESS_GEN_SPACING",0x8E77);
    ADDVAR("TESS_GEN_VERTEX_ORDER",0x8E78);
    ADDVAR("TEXTURE",0x1702);
    ADDVAR("TEXTURE_1D",0x0DE0);
    ADDVAR("TEXTURE_1D_ARRAY",0x8C18);
    ADDVAR("TEXTURE_2D",0x0DE1);
    ADDVAR("TEXTURE_2D_ARRAY",0x8C1A);
    ADDVAR("TEXTURE_2D_MULTISAMPLE",0x9100);
    ADDVAR("TEXTURE_2D_MULTISAMPLE_ARRAY",0x9102);
    ADDVAR("TEXTURE_3D",0x806F);
    ADDVAR("TEXTURE_ALPHA_SIZE",0x805F);
    ADDVAR("TEXTURE_ALPHA_TYPE",0x8C13);
    ADDVAR("TEXTURE_BASE_LEVEL",0x813C);
    ADDVAR("TEXTURE_BINDING_1D",0x8068);
    ADDVAR("TEXTURE_BINDING_1D_ARRAY",0x8C1C);
    ADDVAR("TEXTURE_BINDING_2D",0x8069);
    ADDVAR("TEXTURE_BINDING_2D_ARRAY",0x8C1D);
    ADDVAR("TEXTURE_BINDING_2D_MULTISAMPLE",0x9104);
    ADDVAR("TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY",0x9105);
    ADDVAR("TEXTURE_BINDING_3D",0x806A);
    ADDVAR("TEXTURE_BINDING_BUFFER",0x8C2C);
    ADDVAR("TEXTURE_BINDING_CUBE_MAP",0x8514);
    ADDVAR("TEXTURE_BINDING_CUBE_MAP_ARRAY",0x900A);
    ADDVAR("TEXTURE_BINDING_RECTANGLE",0x84F6);
    ADDVAR("TEXTURE_BLUE_SIZE",0x805E);
    ADDVAR("TEXTURE_BLUE_TYPE",0x8C12);
    ADDVAR("TEXTURE_BORDER_COLOR",0x1004);
    ADDVAR("TEXTURE_BUFFER",0x8C2A);
    ADDVAR("TEXTURE_BUFFER_BINDING",0x8C2A);
    ADDVAR("TEXTURE_BUFFER_DATA_STORE_BINDING",0x8C2D);
    ADDVAR("TEXTURE_BUFFER_OFFSET",0x919D);
    ADDVAR("TEXTURE_BUFFER_OFFSET_ALIGNMENT",0x919F);
    ADDVAR("TEXTURE_BUFFER_SIZE",0x919E);
    ADDVAR("TEXTURE_COMPARE_FUNC",0x884D);
    ADDVAR("TEXTURE_COMPARE_MODE",0x884C);
    ADDVAR("TEXTURE_COMPRESSED",0x86A1);
    ADDVAR("TEXTURE_COMPRESSED_BLOCK_HEIGHT",0x82B2);
    ADDVAR("TEXTURE_COMPRESSED_BLOCK_SIZE",0x82B3);
    ADDVAR("TEXTURE_COMPRESSED_BLOCK_WIDTH",0x82B1);
    ADDVAR("TEXTURE_COMPRESSED_IMAGE_SIZE",0x86A0);
    ADDVAR("TEXTURE_COMPRESSION_HINT",0x84EF);
    ADDVAR("TEXTURE_CUBE_MAP",0x8513);
    ADDVAR("TEXTURE_CUBE_MAP_ARRAY",0x9009);
    ADDVAR("TEXTURE_CUBE_MAP_NEGATIVE_X",0x8516);
    ADDVAR("TEXTURE_CUBE_MAP_NEGATIVE_Y",0x8518);
    ADDVAR("TEXTURE_CUBE_MAP_NEGATIVE_Z",0x851A);
    ADDVAR("TEXTURE_CUBE_MAP_POSITIVE_X",0x8515);
    ADDVAR("TEXTURE_CUBE_MAP_POSITIVE_Y",0x8517);
    ADDVAR("TEXTURE_CUBE_MAP_POSITIVE_Z",0x8519);
    ADDVAR("TEXTURE_CUBE_MAP_SEAMLESS",0x884F);
    ADDVAR("TEXTURE_DEPTH",0x8071);
    ADDVAR("TEXTURE_DEPTH_SIZE",0x884A);
    ADDVAR("TEXTURE_DEPTH_TYPE",0x8C16);
    ADDVAR("TEXTURE_FETCH_BARRIER_BIT",0x00000008);
    ADDVAR("TEXTURE_FIXED_SAMPLE_LOCATIONS",0x9107);
    ADDVAR("TEXTURE_GATHER",0x82A2);
    ADDVAR("TEXTURE_GATHER_SHADOW",0x82A3);
    ADDVAR("TEXTURE_GREEN_SIZE",0x805D);
    ADDVAR("TEXTURE_GREEN_TYPE",0x8C11);
    ADDVAR("TEXTURE_HEIGHT",0x1001);
    ADDVAR("TEXTURE_IMAGE_FORMAT",0x828F);
    ADDVAR("TEXTURE_IMAGE_TYPE",0x8290);
    ADDVAR("TEXTURE_IMMUTABLE_FORMAT",0x912F);
    ADDVAR("TEXTURE_IMMUTABLE_LEVELS",0x82DF);
    ADDVAR("TEXTURE_INTERNAL_FORMAT",0x1003);
    ADDVAR("TEXTURE_LOD_BIAS",0x8501);
    ADDVAR("TEXTURE_MAG_FILTER",0x2800);
    ADDVAR("TEXTURE_MAX_LEVEL",0x813D);
    ADDVAR("TEXTURE_MAX_LOD",0x813B);
    ADDVAR("TEXTURE_MIN_FILTER",0x2801);
    ADDVAR("TEXTURE_MIN_LOD",0x813A);
    ADDVAR("TEXTURE_RECTANGLE",0x84F5);
    ADDVAR("TEXTURE_RED_SIZE",0x805C);
    ADDVAR("TEXTURE_RED_TYPE",0x8C10);
    ADDVAR("TEXTURE_SAMPLES",0x9106);
    ADDVAR("TEXTURE_SHADOW",0x82A1);
    ADDVAR("TEXTURE_SHARED_SIZE",0x8C3F);
    ADDVAR("TEXTURE_STENCIL_SIZE",0x88F1);
    ADDVAR("TEXTURE_SWIZZLE_A",0x8E45);
    ADDVAR("TEXTURE_SWIZZLE_B",0x8E44);
    ADDVAR("TEXTURE_SWIZZLE_G",0x8E43);
    ADDVAR("TEXTURE_SWIZZLE_R",0x8E42);
    ADDVAR("TEXTURE_SWIZZLE_RGBA",0x8E46);
    ADDVAR("TEXTURE_UPDATE_BARRIER_BIT",0x00000100);
    ADDVAR("TEXTURE_VIEW",0x82B5);
    ADDVAR("TEXTURE_VIEW_MIN_LAYER",0x82DD);
    ADDVAR("TEXTURE_VIEW_MIN_LEVEL",0x82DB);
    ADDVAR("TEXTURE_VIEW_NUM_LAYERS",0x82DE);
    ADDVAR("TEXTURE_VIEW_NUM_LEVELS",0x82DC);
    ADDVAR("TEXTURE_WIDTH",0x1000);
    ADDVAR("TEXTURE_WRAP_R",0x8072);
    ADDVAR("TEXTURE_WRAP_S",0x2802);
    ADDVAR("TEXTURE_WRAP_T",0x2803);
    ADDVAR("TEXTURE0",0x84C0);
    ADDVAR("TEXTURE1",0x84C1);
    ADDVAR("TEXTURE10",0x84CA);
    ADDVAR("TEXTURE11",0x84CB);
    ADDVAR("TEXTURE12",0x84CC);
    ADDVAR("TEXTURE13",0x84CD);
    ADDVAR("TEXTURE14",0x84CE);
    ADDVAR("TEXTURE15",0x84CF);
    ADDVAR("TEXTURE16",0x84D0);
    ADDVAR("TEXTURE17",0x84D1);
    ADDVAR("TEXTURE18",0x84D2);
    ADDVAR("TEXTURE19",0x84D3);
    ADDVAR("TEXTURE2",0x84C2);
    ADDVAR("TEXTURE20",0x84D4);
    ADDVAR("TEXTURE21",0x84D5);
    ADDVAR("TEXTURE22",0x84D6);
    ADDVAR("TEXTURE23",0x84D7);
    ADDVAR("TEXTURE24",0x84D8);
    ADDVAR("TEXTURE25",0x84D9);
    ADDVAR("TEXTURE26",0x84DA);
    ADDVAR("TEXTURE27",0x84DB);
    ADDVAR("TEXTURE28",0x84DC);
    ADDVAR("TEXTURE29",0x84DD);
    ADDVAR("TEXTURE3",0x84C3);
    ADDVAR("TEXTURE30",0x84DE);
    ADDVAR("TEXTURE31",0x84DF);
    ADDVAR("TEXTURE4",0x84C4);
    ADDVAR("TEXTURE5",0x84C5);
    ADDVAR("TEXTURE6",0x84C6);
    ADDVAR("TEXTURE7",0x84C7);
    ADDVAR("TEXTURE8",0x84C8);
    ADDVAR("TEXTURE9",0x84C9);
    ADDVAR("TIME_ELAPSED",0x88BF);
    ADDVAR("TIMEOUT_EXPIRED",0x911B);
    ADDVAR("TIMEOUT_IGNORED",0xFFFFFFFFFFFFFFFFull);
    ADDVAR("TIMESTAMP",0x8E28);
    ADDVAR("TOP_LEVEL_ARRAY_SIZE",0x930C);
    ADDVAR("TOP_LEVEL_ARRAY_STRIDE",0x930D);
    ADDVAR("TRANSFORM_FEEDBACK",0x8E22);
    ADDVAR("TRANSFORM_FEEDBACK_ACTIVE",0x8E24);
    ADDVAR("TRANSFORM_FEEDBACK_BARRIER_BIT",0x00000800);
    ADDVAR("TRANSFORM_FEEDBACK_BINDING",0x8E25);
    ADDVAR("TRANSFORM_FEEDBACK_BUFFER",0x8C8E);
    ADDVAR("TRANSFORM_FEEDBACK_BUFFER_ACTIVE",0x8E24);
    ADDVAR("TRANSFORM_FEEDBACK_BUFFER_BINDING",0x8C8F);
    ADDVAR("TRANSFORM_FEEDBACK_BUFFER_INDEX",0x934B);
    ADDVAR("TRANSFORM_FEEDBACK_BUFFER_MODE",0x8C7F);
    ADDVAR("TRANSFORM_FEEDBACK_BUFFER_PAUSED",0x8E23);
    ADDVAR("TRANSFORM_FEEDBACK_BUFFER_SIZE",0x8C85);
    ADDVAR("TRANSFORM_FEEDBACK_BUFFER_START",0x8C84);
    ADDVAR("TRANSFORM_FEEDBACK_BUFFER_STRIDE",0x934C);
    ADDVAR("TRANSFORM_FEEDBACK_PAUSED",0x8E23);
    ADDVAR("TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN",0x8C88);
    ADDVAR("TRANSFORM_FEEDBACK_VARYING",0x92F4);
    ADDVAR("TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH",0x8C76);
    ADDVAR("TRANSFORM_FEEDBACK_VARYINGS",0x8C83);
    ADDVAR("TRIANGLE_FAN",0x0006);
    ADDVAR("TRIANGLE_STRIP",0x0005);
    ADDVAR("TRIANGLE_STRIP_ADJACENCY",0x000D);
    ADDVAR("TRIANGLES",0x0004);
    ADDVAR("TRIANGLES_ADJACENCY",0x000C);
    ADDVAR("TRUE",1);
    ADDVAR("TYPE",0x92FA);
    ADDVAR("UNDEFINED_VERTEX",0x8260);
    ADDVAR("UNIFORM",0x92E1);
    ADDVAR("UNIFORM_ARRAY_STRIDE",0x8A3C);
    ADDVAR("UNIFORM_ATOMIC_COUNTER_BUFFER_INDEX",0x92DA);
    ADDVAR("UNIFORM_BARRIER_BIT",0x00000004);
    ADDVAR("UNIFORM_BLOCK",0x92E2);
    ADDVAR("UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES",0x8A43);
    ADDVAR("UNIFORM_BLOCK_ACTIVE_UNIFORMS",0x8A42);
    ADDVAR("UNIFORM_BLOCK_BINDING",0x8A3F);
    ADDVAR("UNIFORM_BLOCK_DATA_SIZE",0x8A40);
    ADDVAR("UNIFORM_BLOCK_INDEX",0x8A3A);
    ADDVAR("UNIFORM_BLOCK_NAME_LENGTH",0x8A41);
    ADDVAR("UNIFORM_BLOCK_REFERENCED_BY_COMPUTE_SHADER",0x90EC);
    ADDVAR("UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER",0x8A46);
    ADDVAR("UNIFORM_BLOCK_REFERENCED_BY_GEOMETRY_SHADER",0x8A45);
    ADDVAR("UNIFORM_BLOCK_REFERENCED_BY_TESS_CONTROL_SHADER",0x84F0);
    ADDVAR("UNIFORM_BLOCK_REFERENCED_BY_TESS_EVALUATION_SHADER",0x84F1);
    ADDVAR("UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER",0x8A44);
    ADDVAR("UNIFORM_BUFFER",0x8A11);
    ADDVAR("UNIFORM_BUFFER_BINDING",0x8A28);
    ADDVAR("UNIFORM_BUFFER_OFFSET_ALIGNMENT",0x8A34);
    ADDVAR("UNIFORM_BUFFER_SIZE",0x8A2A);
    ADDVAR("UNIFORM_BUFFER_START",0x8A29);
    ADDVAR("UNIFORM_IS_ROW_MAJOR",0x8A3E);
    ADDVAR("UNIFORM_MATRIX_STRIDE",0x8A3D);
    ADDVAR("UNIFORM_NAME_LENGTH",0x8A39);
    ADDVAR("UNIFORM_OFFSET",0x8A3B);
    ADDVAR("UNIFORM_SIZE",0x8A38);
    ADDVAR("UNIFORM_TYPE",0x8A37);
    ADDVAR("UNPACK_ALIGNMENT",0x0CF5);
    ADDVAR("UNPACK_COMPRESSED_BLOCK_DEPTH",0x9129);
    ADDVAR("UNPACK_COMPRESSED_BLOCK_HEIGHT",0x9128);
    ADDVAR("UNPACK_COMPRESSED_BLOCK_SIZE",0x912A);
    ADDVAR("UNPACK_COMPRESSED_BLOCK_WIDTH",0x9127);
    ADDVAR("UNPACK_IMAGE_HEIGHT",0x806E);
    ADDVAR("UNPACK_LSB_FIRST",0x0CF1);
    ADDVAR("UNPACK_ROW_LENGTH",0x0CF2);
    ADDVAR("UNPACK_SKIP_IMAGES",0x806D);
    ADDVAR("UNPACK_SKIP_PIXELS",0x0CF4);
    ADDVAR("UNPACK_SKIP_ROWS",0x0CF3);
    ADDVAR("UNPACK_SWAP_BYTES",0x0CF0);
    ADDVAR("UNSIGNALED",0x9118);
    ADDVAR("UNSIGNED_BYTE",0x1401);
    ADDVAR("UNSIGNED_BYTE_2_3_3_REV",0x8362);
    ADDVAR("UNSIGNED_BYTE_3_3_2",0x8032);
    ADDVAR("UNSIGNED_INT",0x1405);
    ADDVAR("UNSIGNED_INT_10_10_10_2",0x8036);
    ADDVAR("UNSIGNED_INT_10F_11F_11F_REV",0x8C3B);
    ADDVAR("UNSIGNED_INT_2_10_10_10_REV",0x8368);
    ADDVAR("UNSIGNED_INT_24_8",0x84FA);
    ADDVAR("UNSIGNED_INT_5_9_9_9_REV",0x8C3E);
    ADDVAR("UNSIGNED_INT_8_8_8_8",0x8035);
    ADDVAR("UNSIGNED_INT_8_8_8_8_REV",0x8367);
    ADDVAR("UNSIGNED_INT_ATOMIC_COUNTER",0x92DB);
    ADDVAR("UNSIGNED_INT_IMAGE_1D",0x9062);
    ADDVAR("UNSIGNED_INT_IMAGE_1D_ARRAY",0x9068);
    ADDVAR("UNSIGNED_INT_IMAGE_2D",0x9063);
    ADDVAR("UNSIGNED_INT_IMAGE_2D_ARRAY",0x9069);
    ADDVAR("UNSIGNED_INT_IMAGE_2D_MULTISAMPLE",0x906B);
    ADDVAR("UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_ARRAY",0x906C);
    ADDVAR("UNSIGNED_INT_IMAGE_2D_RECT",0x9065);
    ADDVAR("UNSIGNED_INT_IMAGE_3D",0x9064);
    ADDVAR("UNSIGNED_INT_IMAGE_BUFFER",0x9067);
    ADDVAR("UNSIGNED_INT_IMAGE_CUBE",0x9066);
    ADDVAR("UNSIGNED_INT_IMAGE_CUBE_MAP_ARRAY",0x906A);
    ADDVAR("UNSIGNED_INT_SAMPLER_1D",0x8DD1);
    ADDVAR("UNSIGNED_INT_SAMPLER_1D_ARRAY",0x8DD6);
    ADDVAR("UNSIGNED_INT_SAMPLER_2D",0x8DD2);
    ADDVAR("UNSIGNED_INT_SAMPLER_2D_ARRAY",0x8DD7);
    ADDVAR("UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE",0x910A);
    ADDVAR("UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY",0x910D);
    ADDVAR("UNSIGNED_INT_SAMPLER_2D_RECT",0x8DD5);
    ADDVAR("UNSIGNED_INT_SAMPLER_3D",0x8DD3);
    ADDVAR("UNSIGNED_INT_SAMPLER_BUFFER",0x8DD8);
    ADDVAR("UNSIGNED_INT_SAMPLER_CUBE",0x8DD4);
    ADDVAR("UNSIGNED_INT_SAMPLER_CUBE_MAP_ARRAY",0x900F);
    ADDVAR("UNSIGNED_INT_VEC2",0x8DC6);
    ADDVAR("UNSIGNED_INT_VEC3",0x8DC7);
    ADDVAR("UNSIGNED_INT_VEC4",0x8DC8);
    ADDVAR("UNSIGNED_NORMALIZED",0x8C17);
    ADDVAR("UNSIGNED_SHORT",0x1403);
    ADDVAR("UNSIGNED_SHORT_1_5_5_5_REV",0x8366);
    ADDVAR("UNSIGNED_SHORT_4_4_4_4",0x8033);
    ADDVAR("UNSIGNED_SHORT_4_4_4_4_REV",0x8365);
    ADDVAR("UNSIGNED_SHORT_5_5_5_1",0x8034);
    ADDVAR("UNSIGNED_SHORT_5_6_5",0x8363);
    ADDVAR("UNSIGNED_SHORT_5_6_5_REV",0x8364);
    ADDVAR("UPPER_LEFT",0x8CA2);
    ADDVAR("VALIDATE_STATUS",0x8B83);
    ADDVAR("VENDOR",0x1F00);
    ADDVAR("VERSION",0x1F02);
    ADDVAR("VERSION_1_0",1);
    ADDVAR("VERSION_1_1",1);
    ADDVAR("VERSION_1_2",1);
    ADDVAR("VERSION_1_3",1);
    ADDVAR("VERSION_1_4",1);
    ADDVAR("VERSION_1_5",1);
    ADDVAR("VERSION_2_0",1);
    ADDVAR("VERSION_2_1",1);
    ADDVAR("VERSION_3_0",1);
    ADDVAR("VERSION_3_1",1);
    ADDVAR("VERSION_3_3",1);
    ADDVAR("VERSION_4_0",1);
    ADDVAR("VERSION_4_1",1);
    ADDVAR("VERSION_4_2",1);
    ADDVAR("VERSION_4_3",1);
    ADDVAR("VERSION_4_4",1);
    ADDVAR("VERTEX_ARRAY",0x8074);
    ADDVAR("VERTEX_ARRAY_BINDING",0x85B5);
    ADDVAR("VERTEX_ATTRIB_ARRAY_BARRIER_BIT",0x00000001);
    ADDVAR("VERTEX_ATTRIB_ARRAY_BUFFER_BINDING",0x889F);
    ADDVAR("VERTEX_ATTRIB_ARRAY_DIVISOR",0x88FE);
    ADDVAR("VERTEX_ATTRIB_ARRAY_ENABLED",0x8622);
    ADDVAR("VERTEX_ATTRIB_ARRAY_INTEGER",0x88FD);
    ADDVAR("VERTEX_ATTRIB_ARRAY_LONG",0x874E);
    ADDVAR("VERTEX_ATTRIB_ARRAY_NORMALIZED",0x886A);
    ADDVAR("VERTEX_ATTRIB_ARRAY_POINTER",0x8645);
    ADDVAR("VERTEX_ATTRIB_ARRAY_SIZE",0x8623);
    ADDVAR("VERTEX_ATTRIB_ARRAY_STRIDE",0x8624);
    ADDVAR("VERTEX_ATTRIB_ARRAY_TYPE",0x8625);
    ADDVAR("VERTEX_ATTRIB_BINDING",0x82D4);
    ADDVAR("VERTEX_ATTRIB_RELATIVE_OFFSET",0x82D5);
    ADDVAR("VERTEX_BINDING_BUFFER",0x8F4F);
    ADDVAR("VERTEX_BINDING_DIVISOR",0x82D6);
    ADDVAR("VERTEX_BINDING_OFFSET",0x82D7);
    ADDVAR("VERTEX_BINDING_STRIDE",0x82D8);
    ADDVAR("VERTEX_PROGRAM_POINT_SIZE",0x8642);
    ADDVAR("VERTEX_SHADER",0x8B31);
    ADDVAR("VERTEX_SHADER_BIT",0x00000001);
    ADDVAR("VERTEX_SUBROUTINE",0x92E8);
    ADDVAR("VERTEX_SUBROUTINE_UNIFORM",0x92EE);
    ADDVAR("VERTEX_TEXTURE",0x829B);
    ADDVAR("VIEW_CLASS_128_BITS",0x82C4);
    ADDVAR("VIEW_CLASS_16_BITS",0x82CA);
    ADDVAR("VIEW_CLASS_24_BITS",0x82C9);
    ADDVAR("VIEW_CLASS_32_BITS",0x82C8);
    ADDVAR("VIEW_CLASS_48_BITS",0x82C7);
    ADDVAR("VIEW_CLASS_64_BITS",0x82C6);
    ADDVAR("VIEW_CLASS_8_BITS",0x82CB);
    ADDVAR("VIEW_CLASS_96_BITS",0x82C5);
    ADDVAR("VIEW_CLASS_BPTC_FLOAT",0x82D3);
    ADDVAR("VIEW_CLASS_BPTC_UNORM",0x82D2);
    ADDVAR("VIEW_CLASS_RGTC1_RED",0x82D0);
    ADDVAR("VIEW_CLASS_RGTC2_RG",0x82D1);
    ADDVAR("VIEW_CLASS_S3TC_DXT1_RGB",0x82CC);
    ADDVAR("VIEW_CLASS_S3TC_DXT1_RGBA",0x82CD);
    ADDVAR("VIEW_CLASS_S3TC_DXT3_RGBA",0x82CE);
    ADDVAR("VIEW_CLASS_S3TC_DXT5_RGBA",0x82CF);
    ADDVAR("VIEW_COMPATIBILITY_CLASS",0x82B6);
    ADDVAR("VIEWPORT",0x0BA2);
    ADDVAR("VIEWPORT_BOUNDS_RANGE",0x825D);
    ADDVAR("VIEWPORT_INDEX_PROVOKING_VERTEX",0x825F);
    ADDVAR("VIEWPORT_SUBPIXEL_BITS",0x825C);
    ADDVAR("WAIT_FAILED",0x911D);
    ADDVAR("WRITE_ONLY",0x88B9);
    ADDVAR("XOR",0x1506);
    ADDVAR("ZERO",0);
    ENDTABLE("GL");
}

}
