#ifndef LUAAL_ENUMS_H
#define LUAAL_ENUMS_H
#include "shared.h"

namespace LuaApi {
	enum SEB_SourceType {
        SST_UNDETERMINED = AL_UNDETERMINED,
        SST_STATIC = AL_STATIC,
        SST_STREAMING = AL_STREAMING
    };
    
    enum SEB_SourceState {
        SSS_INITIAL = AL_INITIAL,
        SSS_PLAYING = AL_PLAYING,
        SSS_PAUSED = AL_PAUSED,
        SSS_STOPPED = AL_STOPPED
    };
    
    enum SCP_DistanceModel {
        SDM_INVERSE_DISTANCE = AL_INVERSE_DISTANCE,
        SDM_INVERSE_DISTANCE_CLAMPED = AL_INVERSE_DISTANCE_CLAMPED,
        SDM_LINEAR_DISTANCE = AL_LINEAR_DISTANCE,
        SDM_LINEAR_DISTANCE_CLAMPED = AL_LINEAR_DISTANCE_CLAMPED,
        SDM_EXPONENT_DISTANCE = AL_EXPONENT_DISTANCE,
        SDM_EXPONENT_DISTANCE_CLAMPED = AL_EXPONENT_DISTANCE_CLAMPED
    };
    
    enum SEB_BufferFormat {
        SBF_INVALID = 0,
        SBF_MONO_8 = AL_FORMAT_MONO8,
        SBF_MONO_16 = AL_FORMAT_MONO16,
        SBF_STEREO_8 = AL_FORMAT_STEREO8,
        SBF_STEREO_16 = AL_FORMAT_STEREO16
        
#ifdef AL_EXT_float32
        ,SBF_MONO_F32 = AL_FORMAT_MONO_FLOAT32,
        SBF_STEREO_F32 = AL_FORMAT_STEREO_FLOAT32
#endif
        
#ifdef AL_EXT_double
        ,SBF_MONO_DOUBLE = AL_FORMAT_MONO_DOUBLE_EXT,
        SBF_STEREO_DOUBLE = AL_FORMAT_STEREO_DOUBLE_EXT
#endif
        
#ifdef AL_EXT_MCFORMATS
        ,SBF_QUAD_8 = AL_FORMAT_QUAD8,
        SBF_QUAD_16 = AL_FORMAT_QUAD16,
        SBF_QUAD_32 = AL_FORMAT_QUAD32,
        
        SBF_REAR_8 = AL_FORMAT_REAR8,
        SBF_REAR_16 = AL_FORMAT_REAR16,
        SBF_REAR_32 = AL_FORMAT_REAR32,
        
        SBF_51CHN_8 = AL_FORMAT_51CHN8,
        SBF_51CHN_16 = AL_FORMAT_51CHN16,
        SBF_51CHN_32 = AL_FORMAT_51CHN32,
        
        SBF_61CHN_8 = AL_FORMAT_61CHN8,
        SBF_61CHN_16 = AL_FORMAT_61CHN16,
        SBF_61CHN_32 = AL_FORMAT_61CHN32,
        
        SBF_71CHN_8 = AL_FORMAT_71CHN8,
        SBF_71CHN_16 = AL_FORMAT_71CHN16,
        SBF_71CHN_32 = AL_FORMAT_71CHN32
#endif
    };
}

#endif